### ISSUE TITLE
Selected Item of combobox enable = "false"

### ISSUE THREAD

**Issue by superbigsoft** [TestStack/White#190]
Hi White team,

I have a small problem with controls have enable = "False"

For example, I have a wpf combo box define as:

```
<ComboBox Grid.Row="3" Grid.Column="1" x:Name="Gemeinde" DisplayMemberPath="Name" IsEnabled="False"/>
```

And I use white to get the selected value of this combobox

```
public ComboBox CbxGemeinde {
        get {
            if (m_cbxGemeinde == null) {
                m_cbxGemeinde = GetCombobox("Gemeinde");
            }
            return m_cbxGemeinde;
        }
    }
protected ComboBox GetCombobox(string controlId) {
        return Screen.Get(SearchCriteria.ByAutomationId(controlId)) as ComboBox;
    }
```

But the value get from combobox are:
combobox.SelectedItem is null, 
combobox.Items is empty, 
combobox.SelectedItemText = ""

Could you please help me check what wrong in getting selected value of combo box?

Thanks,
Nam

**Comment by ponprabhu** [comment]
Hi Team,
 I am currently facing the same issue. When combobox is disabled i can't get the items inside it.
Is this issue fixed?

Thanks

**Comment by ponprabhu** [comment]
I have used another technique to get the selected item from the disabled dropdownlist. 
Thanks.

**Comment by JakeGinnivan** [comment]
Would you be able to post your findings to help others?

**Comment by ponprabhu** [comment]
For My scenario, I have to take a selected item text from the disabled combobox. So I have just assigned the combobox automation element into textbox and take a value from the textbox like below.

 var groupChild = _contentOwnerGroupElement.FindFirst(TreeScope.Children, new PropertyCondition(AutomationElement.ControlTypeProperty, ControlType.Group));
                    var comboElement = groupChild.FindFirst(TreeScope.Children, new PropertyCondition(AutomationElement.ControlTypeProperty, ControlType.ComboBox));
                    ownerText = new TextBox(comboElement, AppContext.ActionListener);
var selectedValue = ownerText.Text

**Comment by Doctor119** [comment]
I am also trying to get SelectedText from a disabled ComboBox, and the above workaround does not work for me. I get an error.

> 'AutomationElement for TextBox. AutomationId:uxNewBrandCodingLevelComboBox, Name:, ControlType:combo box, FrameworkId:WPF supports neither ValuePattern or TextPattern'
