### ISSUE TITLE
White unable to action on 3rd or more level MenuItems

### ISSUE THREAD

**Issue by ashokkn** [TestStack/White#243]
Hello

I have got MenuItems in my desktop application which are at multiple levels starting from the root. Through White i was successfully able to action upon the MenuItems up till 2nd level, but anything beyond that is a problem

My Code to access the 3rd level item:
       MenuBar qbMenu = app.GetWindow(win.Name).MenuBar;
                TestStack.White.UIItems.MenuItems.Menu m2 = qbMenu.MenuItem(level1, level2);
                m2.SubMenu(SearchCriteria.ByText(level3)).Click();

Screenshot of my app menu bar and items:
![screen shot 2014-06-03 at 9 29 02 am 2](https://cloud.githubusercontent.com/assets/7577538/3156116/ff82ba2e-ead3-11e3-8c16-e7bf06a5d8f3.png)

Exception message: Object reference not set to an instance of the object
This is from line number 3, where "SearchCriteria.ByText(level3)" is returning null and hence a click cannot be performed.

But even when i try to directly pass the item name as a string, exception happens with a message saying "Item not found"

Not sure if i am doing something wrong here (or) there a different technique to access the 3rd or more level menu items (or) its a problem in White.

Please assist.

**Comment by PreetiTech** [comment]
Thank You So much ilya-murzinov your post is really helpful. Please post about accessing table rows and it's particular cell data in teststack.white.
