### ISSUE TITLE
DrawHighlight now working

### ISSUE THREAD

**Issue by ilia-murzinov** [TestStack/White#251]
```
Invalid managed/unmanaged type combination
(Int32/UInt32 must be paired with I4, U4, or Error)
```

**Comment by bpiepiora** [comment]
Version 0.13.3.0 still throws exception "Invalid managed/unmanaged type combination (Int32/UInt32 must be paired with I4, U4, or Error)"

**Comment by Roemer** [comment]
Still not fixed.

**Comment by mkonkolowicz** [comment]
Still not fixed

**Comment by rasmusir** [comment]
Still not fixed, would do it myself if I know how or where to start.

**Comment by jens-gellynck** [comment]
I also have this issue. I suspect this is only happening on 64-bit systems? Are we any closer to a fix or should I have a try myself?

**Comment by jens-gellynck** [comment]
FYI, fixed by downloading repo and rebuilding on my system
