### ISSUE TITLE
can not obtain TabItem via window.Get<TabPage>("Control");

### ISSUE THREAD

**Issue by jeehakim** [TestStack/White#289]
I have a Tab called "Control"

The Inspect program shows below information - 
Name:	"Control"
ControlType:	UIA_TabItemControlTypeId (0xC363)
LocalizedControlType:	"tab item"

I tried both
window.Get<TabPage>("Control");
and
window.Get<Tab>("Control");

But I get

Result Message:	TestStack.White.AutomationException : Failed to get ControlType=tab item,AutomationId=Control
or
Result Message:	TestStack.White.AutomationException : Failed to get ControlType=tab ,AutomationId=Control

I'd like to select tabs and different tabs. How do I select certain tab when both of above fails to get the object?

**Comment by pgurbal** [comment]
Hi,

please check http://docs.teststack.net/White/UIItems.html for the means on how to locate a controls on the page. 
From what you posted it seems, that you are mixing up control's Name and AutomationId - those are two different things.
When calling "window.Get("Control");", White will look for a control based on the AutomationId by default. (AutomationId=="Control")

I guess in your case the command should look something like

window.Get<TabItem>(SearchCriteria.ByText("Control"));

Give it a try ;)

Pavol

**Comment by jeehakim** [comment]
You are right. Somehow this Tab Item control did not have any AutomationID associated with it or the Inspect program didn't give me one. Can anyone explain where this AutomationID is coming from? Is it something to be specified during product code development or should Inspect have caught it (and it is a bug); or else?

So there is no way to grab the Tab (or Tab Page which seems to be the right one here, though it is confusing) by casting <Tab> or <TabPage>? I have multiple text "Control" on my UI.

**Comment by JakeGinnivan** [comment]
The automation id has to be set in code. In wpf it normally comes from the `Id` or the `AutomationProperties.AutomationId` attached property.

**Comment by jeehakim** [comment]
Thanks, Jake.

I've noticed most of window.Get(...) calls take any where from 40 sec to 90 sec to grab the control object...Is this common for White?

**Comment by JakeGinnivan** [comment]
It can do for winforms and large applications.

Building [this](https://github.com/TestStack/White/tree/UIAComWrapper) from source may give you better performance, but it has quite a few failing tests so you might need to manually fix things
