### ISSUE TITLE
Step by Step tutorial for teststack.White 

### ISSUE THREAD

**Issue by jenwei931005** [TestStack/White#293]
I am a new user for teststack.White and I really don't understand how to get start with White.
I am wish to use teststack,White to automated testing with silverlight application.
Please give me some Step by step information for how to getting start with White, and how to automated testing for silverlight application.
Thank for the time to read this and answering my question.

**Comment by pgurbal** [comment]
Hi,

I would recommend to check http://docs.teststack.net/White/GettingStarted.html. There you have at least basic steps on how to start with TestStack.

**Comment by jenwei931005** [comment]
hi pgurbal,

Thanks for the advice, I am really not understand what to do, after I read that.
all the code there, need run with visual studio? and I just create a new project in visual studio for C#?

**Comment by pgurbal** [comment]
Hi :)

yes - this all is C# code, which you write and run as part of some testing project in visual studio. There are plenty of tutorials on the web - google will help.
Examples:
https://www.google.sk/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=visual%20studio%20create%20test%20project
https://www.google.sk/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=nunit%20tutorial%20c%23

**Comment by JakeGinnivan** [comment]
Silverlight is not really support anymore. It had no tests/documentation when I picked up the library and I am not willing to invest time in it when there are so many other things to focus on in White. 

That said there should be some blog posts around if you have a look around.

Here is an article on the subject: http://www.codeproject.com/Articles/35042/Automated-Testing-in-Silverlight

**Comment by JakeGinnivan** [comment]
Here is another - https://social.msdn.microsoft.com/Forums/silverlight/en-US/cc41e065-7012-4096-9dc1-4d008881e523/silverlight-testing-with-white-trying-to-login-via-silverlight-business-application-templates?forum=silverlightarchieve

**Comment by jenwei931005** [comment]
Thanks pgurbal and Jake,
Can I know what project should I create in VS? is it asp.NET Web Application? or others?
and do I use xunit is correct for silverlight c#?

**Comment by jenwei931005** [comment]
Hi Pgurbal and Jake,

Is that only Visual Studio Ultimate or Visual Studio Premium can do the UI Test?
that's mean I can't do anything for automated UI Test using Visual Studio Professional right?
Do you know about others open source Automated testing tools for silverlight?

**Comment by JakeGinnivan** [comment]
@jenwei931005 Ultimate and Premium have something called Coded UI which is a commercial UI testing tool.

You can use White with Professional/Community edition. Just create a normal class library project, install xUnit/nUnit or any other test framework library from nuget then you use white within a unit test.

I don't know of any other open source projects doing a similar thing to White.

**Comment by jenwei931005** [comment]
@JakeGinnivan 

Thanks for the reply. You let me much more understand about white.so I need to install XUnit from nuget right? for silverlight.

**Comment by JakeGinnivan** [comment]
Correct, you create a *normal* .net class library, not a silverlight library. In your normal xUnit test you will get White to open a browser, navigate to your silverlight applications URL then you can start automating it

**Comment by jenwei931005** [comment]
@JakeGinnivan  

when I install xunit there come out an error

"
Install failed. Rolling back...
Install-Package : Could not install package 'xunit.extensibility.core 2.0.0'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.0
', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.
At line:1 char:16
+ Install-Package <<<<  xunit -Version 2.0.0
    + CategoryInfo          : NotSpecified: (:) [Install-Package], InvalidOperationException
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PowerShell.Commands.InstallPackageCommand
"

do you know what is this problem and how can I solve this?

**Comment by JakeGinnivan** [comment]
Xunit 2.0 only supports .net 4.5.

Sent from my Windows Phone
________________________________

**Comment by jenwei931005** [comment]
@JakeGinnivan Thanks! You are helping me very much to get familiar to White!

**Comment by jeehakim** [comment]
@JakeGinnivan I have created YouTube demo video on SpecFlow & White for testing UI on .NET based Windows Desktop Application. Please feel free to share for those needed.
@jenwei931005 The 10 min. video should give you better idea of working with White under VisualStudio IDE.

https://youtu.be/LG_0SEeCwh0

**Comment by JakeGinnivan** [comment]
// @mwhelan @robdmoore

**Comment by robdmoore** [comment]
Cool!

**Comment by jenwei931005** [comment]
@jeehakim  Thanks for the video. After viewing your video, I got some question want to ask.

1.Dose the step is the same, while I wan to carry out test for Silverlight?
2. What is the Application you use to identify the object? and what name should I look for or type in? is it " Automation ID" or "Process ID" ? is it same if I use UI SPY?

Thanks for your help

**Comment by JakeGinnivan** [comment]
@jeehakim I have just moved the docs into the repo so it's easier to contribute. Did you want to put a link to your video into the Getting started page on the docs. 

Gonna close out this issue, but anyone in this thread, a PR to improve the getting started docs would be great

**Comment by jeehakim** [comment]
@JakeGinnivan yes, that's fine.

**Comment by jainprachi16** [comment]
Hi,
Does TestStack.White supports ASP.NET or web  application. Is it able to detect Controls on ASP.NET application.

**Comment by dpisanu** [comment]
Hi @jainprachi16 : please have a look at https://github.com/TestStack/White/issues/383

**Comment by jainprachi16** [comment]
Hi @dpisanu ,
Thanks for your reply. I saw #383 but still not getting my answer. What i exactly want to know is:

I am working on a ASP.NET application. The framework which i am using for detecting UI Controls are TestStack.White and Windows Automation. Although the object is having enough properties like Name , Controltype -> Hyperlink and Framework Id -> "Internet Explorer". But still not able to detect control with enough properties.

Do white is able to detect Controls on ASP.NET or Web Application?

**Comment by JakeGinnivan** [comment]
> Do white is able to detect Controls on ASP.NET or Web Application?

Nope, white is for desktop applications. I suggest Selenium instead.

**Comment by dpisanu** [comment]
Hi @jainprachi16 ... maybe you missed it in the linked issue.

"check it with UIAVerify or Inspect. If either of them shows something - then White also should"
But as @JakeGinnivan says. Selenium might be your better bet.

**Comment by jainprachi16** [comment]
Yes. You can

**Comment by Fionalulu** [comment]
Thanks for your reply! But how to debug this solution if there is no executable project as the startup project? You know, there is only one project which contains the class for test methods but it cannot be required in Main.

发自Fiona的 iPhone

在 2018年8月9日，16:27，Prachi jain <notifications@github.com<mailto:notifications@github.com>> 写道：

Yes. You can

**Comment by jainprachi16** [comment]
Which editor you're using. Also can you please elaborate your problem?

**Comment by Fionalulu** [comment]
Hi Prachi, I am using VS 2017 and here is the screenshot of my simple source code 

![code](https://user-images.githubusercontent.com/31311209/43949269-a36aae3e-9cbf-11e8-8f86-de325ee34168.PNG)

but I got the error when starting the debugging

![error](https://user-images.githubusercontent.com/31311209/43949302-ba98d84c-9cbf-11e8-8767-f662db376a90.PNG)

How can I generate the exe file?

**Comment by jainprachi16** [comment]
Right click under test method block and select debug....
