### ISSUE TITLE
Why is there a requirement that methods be marked Virtual?

### ISSUE THREAD

**Issue by Fran71** [TestStack/White#296]
Hello,

If the reason for this is documented somewhere feel free to point me there and close this out.  

I cannot find the reason that White checks method for the virtual modifier prior to executing them.  An exception is thrown if they do not.  Could someone explain why this is necessary?

I understand that the use of Testing libraries (such as NSubstitute) for the API may require this, but what was the reason for requiring consumers of White to mark them as virtual as well? 

Thank you!
Jordan

**Comment by JakeGinnivan** [comment]
Hey,

White uses Castle.Core's dynamic proxies to cross cut retry, and a bunch of other things. To do that methods need to be virtual to allow dynamic proxies to override. Short answer, AOP.

Hope that helps

Sent from my Windows Phone
________________________________
