### ISSUE TITLE
DevExpress XtraMessageBox message Text showing NO FrameworkId and AutomationId

### ISSUE THREAD

**Issue by dm2909** [TestStack/White#305]
There is DevExpress XtraMessageBox used in one of the application. 
TestStack can read MessageBox window Title Button but NOT ABLE TO READ TEXT.
VerifyUI tool also not showing blank FrameworkID and AutomationID as well.

Is there any other way to read the messagebox text???

urgent help will be appreciable.

**Comment by JakeGinnivan** [comment]
It sounds like DevExpress do not support UI Automation for their controls. If thats the case then White will not work for you. 
It is probably worth contacting their support so they can tell you how to do this with their controls. Good luck
