### ISSUE TITLE
DevExpress Checkbox ListBox not able to read

### ISSUE THREAD

**Issue by dm2909** [TestStack/White#306]
DevExpress Checkbox Listbox  llistitems can be readable and event not showing frameworkid in VerifyUI tool.

**Comment by JakeGinnivan** [comment]
As with the other issue, it sounds like DevExpress controls do not implement UI automation. Their support should be able to confirm this. There is not much White can do

**Comment by dm2909** [comment]
Well I have downloaded the UIAComWrapper branch from https://github.com/TestStack/White/tree/UIAComWrapper
and build and replace the new dlls and DevEx Listboxstarts working  :)

But When i use this build it gives some errors to my old code.

**Comment by JakeGinnivan** [comment]
Thats good! That branch is not released as their are a bunch of test failures which need to be fixed :( I have said I will try and organise a weekend i am available to try and get a few people together and make some progress on that branch but will have to see how I go over the next few weeks.
