### ISSUE TITLE
Pull requests with code documentation

### ISSUE THREAD

**Issue by FantasticFiasco** [TestStack/White#310]
I was wondering whether you accept pull requests with added or updated code documentation. I am considering using White for UI tests and will then go thought the source code. For personal benefits I will possibly add or update the existing public API documentation, and am wondering whether those changes would be something you consider beneficial in a pull request.

My second question is regarding your role in White. I read that you have moved focus and am wondering if you are using any other UI test framework for Windows desktop applications or whether any of your other open source projects has priority.

**Comment by Roemer** [comment]
If you're still alive, feel free to create pull requests with code documentation. Just make sure to use an updated fork/branch.
