### ISSUE TITLE
Unable to get Table row,rows.Count returns 0

### ISSUE THREAD

**Issue by ekowu** [TestStack/White#313]
Structure of the Table:
   ■Table (ControlType.Table) 
     ■Header Panel (ControlType.Custom)
     ■Data Panel (ControlType.Custom)

I tried to get table row whith the below code, but  rows.Count return 0 ,so I can't get the row value 
Table table = calcwindow.Get<Table>(SearchCriteria.ByControlType(ControlType.Table).AndAutomationId("gdcAccount"));
            TableRows rows = table.Rows;
            Console.WriteLine(rows.Count);

**Comment by maxinfet** [comment]
Would it be possible to get a screen shot of the structure of the controls from inspect or snoop (or some other tool).

**Comment by ekowu** [comment]
thanks maxinfet,I have solved the problem by reading and changing the source code

when I read  the white source code,I found that when white try to get tablerows , the Structure of the Table may be lay as follows,The Top Row means the header of the table and the "Row numbers" means the rows of the table,and when get cells of one row ,white found by some keywords instead of get the children of the row,I think get children of the row shoud be more accurate.

Tablename
   ---Top Row
   ---Row 1
      ---cell1
      ---cell2
   ---Row 2
   ---.........

but  Structure of my Table as follow, so I get 0 while I used rowcount
Tablename
   ---Head Panel
       ---cell1
       ---cell2
       ---.........
   ---Data Panel
       ---Row 1
          ---cell1
          ---cell2
          ---.........
       ---Row 2
       ---.........

something more
I got nothing when I try to get tableheader because my tableheader name is "Head Panel"  but the default is "Top Row" and I didn't found any document which advice me to concent this unless I read the source code.

**Comment by ekowu** [comment]
sorry the Structure of the Table is format chaos,it shoud be like this:

Tablename
---Top Row
---Row 1
------cell1
------cell2
---Row 2
------.........


Tablename
---Head Panel
------cell1
------cell2
------.........
---Data Panel
------Row 1
---------cell1
---------cell2
---------.........
------Row 2
---------.........

**Comment by maxinfet** [comment]
OK that's what I was expecting, that your table had a different structure than the default. I ran into this problem as well when working with XamDataGrids. I haven't really come up with a solution yet.
