### ISSUE TITLE
UI Automation for Silveright 

### ISSUE THREAD

**Issue by dhimanak** [TestStack/White#318]
I'm trying to automate a silverlight website using TestStack framework. As suggested in some of the forum discussions before, I'm trying to open a website using Watin and later attach the process to white. Getting an exception while retrieving a silverlight document object. 

"An unhandled exception of type 'TestStack.White.Factory.UIItemSearchException' occurred in TestStack.White.WebBrowser.dll.
Additional information: Could not find Silverlight document after waiting for 20000. Timeout value configured by BusyTimeout in White/Core"

Please suggest a solution. Here is the code:
 
            IE watin = new IE("http://www.microsoft.com/silverlight/new-controls/demo/");        
            var config = TestStack.White.Configuration.CoreAppXmlConfiguration.Instance;
            config.BusyTimeout = 20000;                          
            System.Threading.Thread.Sleep(5000);
           
            TestStack.White.WebBrowser.InternetExplorerFactory.Plugin();
            string title = "Microsoft Silverlight - Internet Explorer provided by National Oilwell Varco";
          
            InternetExplorerWindow ieWin = (InternetExplorerWindow)Application.Attach(watin.ProcessID).GetWindow(title);           

            TestStack.White.WebBrowser.Silverlight.SilverlightDocument sl = ieWin.SilverlightDocument;

**Comment by JakeGinnivan** [comment]
White is not going to support silverlight going forward. It will require too much effort to maintain compatibility while trying to add support for Win10 apps and such. Sorry about that, but this is an OSS project which we work on in our own time. 

If you need silverlight support you might need to help out to get the tests running against silverlight again
