### ISSUE TITLE
Mouse Move

### ISSUE THREAD

**Issue by Aghlara** [TestStack/White#321]
Hi,

I am writing some automation but we require to show the mouse movements. We want to simulate exactly what user does, so as when we navigate to different element of form, we want to see the mouse cursor moving on the screen. How do we do that?

Thanks,

**Comment by JakeGinnivan** [comment]
White just sets the point of the mouse, it doesn't move it across the screen. You could probably do it yourself via the `Mouse` class and animate some path to update the position of the mouse.

**Comment by Aghlara** [comment]
Thanks Jake, well that was the actual question. How do we do animate it to be moved across screen?

**Comment by JakeGinnivan** [comment]
You will need to get the location of `Mouse.Instance.Location`, then the position of the element you want to go to. You will then need to calculate a path, then set `Mouse.Instance.Location` for each pixel you want to move through. So it would be entirely manual

**Comment by Aghlara** [comment]
Ok, let's say I do `TestStack.White.InputDevices.Mouse.Instance.Location = new Point(0, 0);` Do we expect that the mouse pointer be moved to `(0,0)` ? I mean visually, the mouse pointer, should it be at that point?

**Comment by JakeGinnivan** [comment]
Yep, that will move the mouse. Though I think White prevents moving to (0, 0) because that is what is returned when the position of an element cannot be found and 0,0 ends up activating window 8's hot corners

**Comment by Aghlara** [comment]
Thanks. I have a feeling that Parallels+Mac does not sync it across. Because I don't see pointer goes to that location. However when I create a snapshot with Greenshot and include the pointer, it actually is in that location!

**Comment by Aghlara** [comment]
I can confirm that is related to `Don't optimize for games` and `Optimize for games` option of the mouse in Parallels.

**Comment by dpisanu** [comment]
Just to quickly pick this up. This is how we do it to have a sort of visual Drag Effect.

public static void DragEffect(Point startPosition, Point endPosition, int pause)
{
   TestStack.White.InputDevices.Mouse.Instance.Location = startPosition;
   TestStack.White.InputDevices.Mouse.LeftDown();
   
   var distanceX = endPosition.X - startPosition.X;
   var distanceY = endPosition.Y - startPosition.Y;
   
   var distance = Math.Sqrt(Math.Pow(distanceX, 2) + Math.Pow(distanceY, 2));
   var stepCount = Math.Ceiling(distance / StepLength);

   var stepLengthX = distanceX / stepCount;
   var stepLengthY = distanceY / stepCount;

   var currentX = startPosition.X;
   var currentY = startPosition.Y;

   for (var i = 0; i < stepCount; i++)
   {
      currentX += stepLengthX;
      currentY += stepLengthY;
      TestStack.White.InputDevices.Mouse.Instance.Location = new Point((int)currentX, (int)currentY);
      Thread.Sleep(pause);
   }
}

**Comment by Aghlara** [comment]
Ah that's useful thanks.
