### ISSUE TITLE
How to generate report after automating the WPF application using white?

### ISSUE THREAD

**Issue by vivek9591** [TestStack/White#323]
Hi,
I just automated wpf application using white. Please, let me know how to generate report in white.

Thanks!

**Comment by ivan-danilov** [comment]
Hi, sorry for late response.
Usually we use NUnit (or other similar framework) to execute automated tests, so we can use its report capabilities.

**Comment by vivek9591** [comment]
Hi ivan-danilov,
Thanks a lot for your help.
