### ISSUE TITLE
Where to find current documentation?

### ISSUE THREAD

**Issue by idvorkin** [TestStack/White#325]
The README.md lists documentation and several other links @ http://docs.teststack.net/. However this website seems to be down.  Is there a current place to check for documentation?

**Comment by TheWhiteWolves** [comment]
https://github.com/TestStack/TestStack.docs/tree/master/_source/White

You can check here for some documentation

**Comment by idvorkin** [comment]
This is helpful!  Should the README.md be updated to these links?

**Comment by TheWhiteWolves** [comment]
most likely but I don't think anyone's had a chance to update it.
