### ISSUE TITLE
Cannot Use SearchCriteria

### ISSUE THREAD

**Issue by xepherys** [TestStack/White#330]
I have White and xunit installed in Visual Studio.  When I try to use SearchCriteria I get an error that it doesn't exist in the current context.  I've tried adding every `using` option for White that there is, and nothing seems to resolve this.  Any thoughts?  Thanks!

**Comment by maxinfet** [comment]
Maybe this  http://stackoverflow.com/questions/33556876/searchcriteria-in-white-cant-find-name-in-current-context is what you need?

**Comment by dpisanu** [comment]
SearchCriteria is on the "TestStack.White.UIItems.Finders" Namespace.
```javascript
using TestStack.White.UIItems.Finders;
```
You need to reference the "TestStack.White.dll" in your Project.
```javascript
    <Reference Include="TestStack.White, Version=1.0.0.0, Culture=neutral, PublicKeyToken=2672efbf3e161801, processorArchitecture=MSIL">
      <SpecificVersion>False</SpecificVersion>
      <HintPath>..\3rdParty\TestStack.White\TestStack.White.dll</HintPath>
    </Reference>
```

If in doubt that SearchCriteria is not resolved properly in your code, go ahead and write the full path to it.
```javascript
application.GetWindow(TestStack.White.UIItems.Finders.SearchCriteria.ByClassName(typeof(OwnWindowControl).Name))
```

Hope this helps.

**Comment by xepherys** [comment]
Somehow, despite swearing that I tried `.Finders`, that did resolve it.  Thanks all!
