### ISSUE TITLE
Can white flash a selected control? 

### ISSUE THREAD

**Issue by ywang0701** [TestStack/White#331]
Scenario:

A control is selected by White, can White flash the selected control? 

Sth like,   window.Get<>...Flash();

Thanks,

**Comment by tboesgaard** [comment]
There is a DrawHighlight-method for UIItems - or you mean something else by "flash?"

**Comment by Roemer** [comment]
Guess the DrawHighlight is what is needed here, as already mentioned. So I'll close this issue.
