### ISSUE TITLE
White Slack

### ISSUE THREAD

**Issue by chebastian** [TestStack/White#332]
I dindt find anything about a Slack Team beeing available anywhere, so i created one. 
https://white-ui.slack.com

Anyone that uses White should join so we can help eachother out with automation using white.
Im using White daily and i know i have a ton of questions i would like to ask people who also use it on a dailybasis, and hopefully i can help someone to!

**Comment by chebastian** [comment]
damn landing page not up yet, pm me for access until its available

**Comment by dpisanu** [comment]
gotten any invite requests from the community yet?

**Comment by ywang0701** [comment]
I will response. I need to register at the site

**Comment by ywang0701** [comment]
I don't have the invitation, please send it again. I am using white as part
of my automation. thx

On Mon, Nov 16, 2015 at 8:25 AM, Yongyan Wang <yongyan.wang@gmail.com>
wrote:

> I will response. I need to register at the site
> On Nov 16, 2015 2:19 AM, "Daniel P" <notifications@github.com> wrote:
>
>> gotten any invite requests from the community yet?
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/TestStack/White/issues/332#issuecomment-156979381>.
>>
>


-- 
Yong Wang
503 593 0582 (cell)

**Comment by JohanLarsson** [comment]
There is also Gitter that does not require invites.

**Comment by JakeGinnivan** [comment]
I suggest using Gitter, any reasons to not to?

**Comment by JakeGinnivan** [comment]
I have added the gitter badge to the readme. I think we should just go with that for the moment

**Comment by chebastian** [comment]
Thanks for the advice Nice!
