### ISSUE TITLE
Accessing the cell with image from DataGrid

### ISSUE THREAD

**Issue by pjapkar** [TestStack/White#336]
I have a DataGrid with first 5 colums as text and next 2 columns as images.
When I get the ListView for the Datagrid then ListView hearder has all 7 columns but ListView header has only first 5 cells.

**Comment by Roemer** [comment]
Can you post a little XAML here for this DataGrid, this makes it easier to debug and help.

**Comment by pjapkar** [comment]
Hi Roemer,

- Please find below the XAML file.
- When I get this grid in ListView. Rows have only 5 cells instead of 7. Last 2 cells which have images do not appear as cells while Columns are 7 columns are available as part of header.

<Grid Grid.Row="2" Margin="0,10,0,0"
          Grid.Column="3"
          VerticalAlignment="Stretch">
            <DataGrid 
                Name="XyzDataGrid"
                Margin="0,0,0,0"
                ItemsSource="{Binding SkuViewModel.Sku.DimensionVariants}"
                SelectedItem="{Binding SelectedCpiSkuDimensionVariant, Mode=TwoWay, UpdateSourceTrigger=PropertyChanged}"
                Background="Black"
                VerticalAlignment="Stretch"
                BorderThickness="0"
                BorderBrush="Transparent">
                
                
                <DataGrid.Columns>
                    <DataGridTemplateColumn SortMemberPath="CreatedDate" Width="Auto" MinWidth="200">
                        <DataGridTemplateColumn.Header>
                            <TextBlock Text="{x:Static Resources:Strings.DimVarDateHeader}"
                                       Foreground="Black"
                                       HorizontalAlignment="Left"/>
                        </DataGridTemplateColumn.Header>
                        <DataGridTemplateColumn.HeaderStyle>
                            <Style TargetType="{x:Type DataGridColumnHeader}">
                                <Setter Property="Background" Value="Transparent"/>
                                <Setter Property="HorizontalAlignment" Value="Left"/>
                                <Setter Property="HorizontalContentAlignment" Value="Left"/>
                                <Setter Property="Width" Value="Auto"/>
                                <Setter Property="BorderThickness" Value="1"/>
                            </Style>
                        </DataGridTemplateColumn.HeaderStyle>
                        <DataGridTemplateColumn.CellTemplate>
                            <DataTemplate>
                                <TextBlock Text="{Binding CreatedDate}" 
                                           Style="{StaticResource DataGridTextStyle}" 
                                           HorizontalAlignment="Left"/>
                            </DataTemplate>
                        </DataGridTemplateColumn.CellTemplate>
                    </DataGridTemplateColumn>

                    <DataGridTemplateColumn SortMemberPath="Length" Width="*" MinWidth="170" >
                        <DataGridTemplateColumn.Header>
                            <TextBlock Text="{x:Static Resources:Strings.LengthHeader}"
                                       Foreground="Black"
                                       ToolTip="{x:Static Resources:Strings.LengthToolTip}"
                                   />
                        </DataGridTemplateColumn.Header>
                        <DataGridTemplateColumn.HeaderStyle>
                            <Style TargetType="{x:Type DataGridColumnHeader}">
                                <Setter Property="Background" Value="Transparent"/>
                                <Setter Property="HorizontalAlignment" Value="Right"/>
                                <Setter Property="HorizontalContentAlignment" Value="Right"/>
                                <Setter Property="Width" Value="Auto"/>
                                <Setter Property="BorderThickness" Value="0"/>
                            </Style>
                        </DataGridTemplateColumn.HeaderStyle>
                        <DataGridTemplateColumn.CellTemplate>
                            <DataTemplate>
                                <TextBlock Text="{Binding Length}"
                       Style="{StaticResource DataGridTextStyle}"
                       Margin="0,0,10,0"
                       TextAlignment="Right"/>
                            </DataTemplate>
                        </DataGridTemplateColumn.CellTemplate>
                    </DataGridTemplateColumn>

                    <DataGridTemplateColumn SortMemberPath="Width" Width="*" MinWidth="170">
                        <DataGridTemplateColumn.Header>
                            <TextBlock Text="{x:Static Resources:Strings.WidthHeader}"
                                       Foreground="Black"
                                       ToolTip="{x:Static Resources:Strings.WidthToolTip}"
                                   />
                        </DataGridTemplateColumn.Header>
                        <DataGridTemplateColumn.HeaderStyle>
                            <Style TargetType="{x:Type DataGridColumnHeader}">
                                <Setter Property="Background" Value="Transparent"/>
                            </Style>
                        </DataGridTemplateColumn.HeaderStyle>
                        <DataGridTemplateColumn.CellTemplate>
                            <DataTemplate>
                                <TextBlock Text="{Binding Width}"
                       Style="{StaticResource DataGridTextStyle}"
                       Margin="0,0,10,0"
                       TextAlignment="Right"/>
                            </DataTemplate>
                        </DataGridTemplateColumn.CellTemplate>
                    </DataGridTemplateColumn>

                    <DataGridTemplateColumn SortMemberPath="Height" Width="*" MinWidth="170">
                        <DataGridTemplateColumn.Header>
                            <TextBlock Text="{x:Static Resources:Strings.HeightHeader}"
                                       Foreground="Black"
                                       ToolTip="{x:Static Resources:Strings.HeightToolTip}"
                                   />
                        </DataGridTemplateColumn.Header>
                        <DataGridTemplateColumn.HeaderStyle>
                            <Style TargetType="{x:Type DataGridColumnHeader}">
                                <Setter Property="Background" Value="Transparent"/>
                            </Style>
                        </DataGridTemplateColumn.HeaderStyle>
                        <DataGridTemplateColumn.CellTemplate>
                            <DataTemplate>
                                <TextBlock Text="{Binding Height}"
                       Style="{StaticResource DataGridTextStyle}"
                       Margin="0,0,10,0"
                       TextAlignment="Right"/>
                            </DataTemplate>
                        </DataGridTemplateColumn.CellTemplate>
                    </DataGridTemplateColumn>

                    <DataGridTemplateColumn SortMemberPath="Weight" Width="*"  MinWidth="170">
                        <DataGridTemplateColumn.Header>
                            <TextBlock Text="{x:Static Resources:Strings.WeightHeader}"
                                       Foreground="Black"
                                       ToolTip="{x:Static Resources:Strings.WeightToolTip}"
                                   />
                        </DataGridTemplateColumn.Header>
                        <DataGridTemplateColumn.HeaderStyle>
                            <Style TargetType="{x:Type DataGridColumnHeader}">
                                <Setter Property="Background" Value="Transparent"/>
                            </Style>
                        </DataGridTemplateColumn.HeaderStyle>
                        <DataGridTemplateColumn.CellTemplate>
                            <DataTemplate>
                                <TextBlock Text="{Binding Weight}"
                                           Margin="0,0,10,0"
                                           Style="{StaticResource DataGridTextStyle}"
                                           TextAlignment="Right"/>
                            </DataTemplate>
                        </DataGridTemplateColumn.CellTemplate>
                    </DataGridTemplateColumn>

                    <DataGridTemplateColumn Width="*" MinWidth="100">
                        
                       

                        <DataGridTemplateColumn.CellTemplate>
                            <DataTemplate>
                                <Image
                                    Height="24"
                                    Width="24"
                                    VerticalAlignment="Center"
                                    HorizontalAlignment="Center"
                                    ToolTip="{x:Static Resources:Strings.DimensionsOutOfBoundsToolTip}"
                                    Visibility="{Binding IsDimensionsOutOfBounds, Converter={valueConverters:TrueToVisibleConverter}}"
                                    Source="../Images/Warning32.png"/>
                            </DataTemplate>
                        </DataGridTemplateColumn.CellTemplate>
                    </DataGridTemplateColumn>
                    
                    
                    <DataGridTemplateColumn Width="*" MinWidth="100">
                        <DataGridTemplateColumn.Header>
                            <TextBlock Text="{x:Static Resources:Strings.DeleteMeHeader}"
                                       Foreground="Black"
                                       ToolTip="{x:Static Resources:Strings.DeleteMeHeaderToolTip}"
                                   />
                        </DataGridTemplateColumn.Header>
                        <DataGridTemplateColumn.HeaderStyle>
                            <Style TargetType="{x:Type DataGridColumnHeader}">
                                <Setter Property="Background" Value="Transparent"/>
                            </Style>
                        </DataGridTemplateColumn.HeaderStyle>
                        

                        <DataGridTemplateColumn.CellTemplate>
                            <DataTemplate>
                                <controls:ImageHoverButton
                                    Command="{Binding DataContext.DeleteDimensionalVariantCommand, RelativeSource={RelativeSource AncestorType={x:Type DataGrid}}}"
                                    CommandParameter="{Binding}"
                                    Height="24"
                                    Width="24"
                                    VerticalAlignment="Center"
                                    HorizontalAlignment="Center"
                                    Visibility="Visible"
                                    NormalSource="../Images/icon-x-red.png"
                                    HoverSource="../Images/icon-x-red-hover.png"/>
                            </DataTemplate>
                        </DataGridTemplateColumn.CellTemplate>
                    </DataGridTemplateColumn>

                </DataGrid.Columns>

            </DataGrid>

            <Border Name="DisableOverlay1"
                  Style="{StaticResource DisableBorderStyle}"
                  Visibility="{Binding IsEditingExisting, Converter={valueConverters:TrueToHiddenConverter}}">
            </Border>

        </Grid>

Thanks,
Prashant

**Comment by dpisanu** [comment]
If I am not mistaking there is a check on what constitutes as a gridcell. 
If it contains anything but a Label it id discarded. Never understood this constraint and we removed it on our branch.
Let me get to a computer to point you to the possible culprit.

**Comment by dpisanu** [comment]
sorry for getting back to you so late.
In the ListViewRow.cs it used to look the following:

```javascript
public virtual ListViewCells Cells
        {
            get
            {
                actionListener.ActionPerforming(this);
                var collection = finder.Descendants(AutomationSearchCondition.ByControlType(ControlType.Text));
                return new ListViewCells(collection, actionListener, header);
            }
        }
```

This limited the Cell Content to only ControlType.Text.
You will need to extend this to also allow other ControlTypes.
For example:

```javascript
var collection = finder.Descendants(new AutomationSearchCondition(
new OrCondition(                                                                                        AutomationSearchCondition.ByControlType(ControlType.Text).Condition,                                                                                        AutomationSearchCondition.ByControlType(ControlType.Image).Condition))
                                                                                        );
```

**Comment by Roemer** [comment]
Fixed this in PR https://github.com/TestStack/White/pull/366

**Comment by dpisanu** [comment]
Danke. Thx.
This has been on my push list for a while.
Never really got around to pushing any of my changes. :p

**Comment by Roemer** [comment]
@dpisanu Feel free to quickly review the PR :)
