### ISSUE TITLE
Impossible to use TestStack White with JAVA app

### ISSUE THREAD

**Issue by juste3alfaza** [TestStack/White#338]
I try TestStack.White to run an automation for JAVA app, here in my example is Calculator coded in JAVA, under VS2015 in C#. I installed TestStack.White using NuGet and tring with Winform app and it works, but here with java app, I can open the application, But not all component I can click on it. So I try to know the component name with UIA Verify interface, but it selects the whole window, after that I look for something similar to UI Verify, and I found Ranorex STudio with Track Features and it works I can see Java Component name, but after I know the name, and I searsh for it in the app, the code not working. This is my code:
    class Program
    {
        static void Main(string[] args)
        {
            Application aa = Application.Launch("..\\..\\CalculatorOrange.jar");
            Window calcWindos = aa.GetWindow("Calculator Lite - 1.5.3", InitializeOption.NoCache);
            Button twoBtn = calcWindos.Get<Button>(SearchCriteria.ByText("8"));
            twoBtn.Click();
            //var twoBtn = calcWindos.Get<MenuBar>("mnuFile");
           //twoBtn.Click();
        }
    }
and it shows this error:

    An unhandled exception of type 'TestStack.White.AutomationException' occurred in TestStack.White.dll

    Additional information: Failed to get (ControlType=button or ControlType=check box),Name=8

This image shows the component type and name , On the left, I use Ranorex Spy, and it shows all the Component, and on the right the Inspect for Microsoft
![untitled](https://cloud.githubusercontent.com/assets/1416851/11422186/d56606a2-9431-11e5-8901-6b5ca152bff2.png)

**Comment by Roemer** [comment]
That is because Java UIs usually do not use Windows Controls for the UI. They render/paint everything on their own. That is why you do not see anything in UIA Verify and therefore cannot test it in White. As far as I know, there is no workaround or fix for this.

**Comment by juste3alfaza** [comment]
I was able to see any of my Swing components (buttons, checkboxes, radio buttons, edit boxes, etc...) with Ranorex Spy, but I think White not recognize  the component. Is there anything I need to do or download to make this work?

**Comment by gaip** [comment]
// if you have VS than maybe you can do that using Automation Element

class Program
{
static void Main(string[] args)
{
Application aa = Application.Launch("..\..\CalculatorOrange.jar");
Window calcWindos = aa.GetWindow("Calculator Lite - 1.5.3",
InitializeOption.NoCache);
//Button twoBtn = calcWindos.GetWindow(SearchCriteria.ByText("8"));

public static  void Start()
     {
         _appProcess = Process.Start(CommonVar.CommonVar.PATH_TO_APPLICATION);
ICATION);
     }



var twoBtn= calcWindows.GetWindow().FindFirst(TreeScope.Descendants, new
PropertyCondition(AutomationElement.NameProperty, "nameButton")));

twoBtn.Click();

            //var twoBtn = calcWindos.Get("mnuFile");
//twoBtn.Click();
}
}


#region Panel (button)

private AutomationElement OpenBtn
        {
            get
            {
                return
MainWindowElement.FindFirst(TreeScope.Descendants, new
PropertyCondition(AutomationElement.NameProperty, "name"));
            }
        }

#endregion



2015-11-26 14:10 GMT+01:00 Roman <notifications@github.com>:

**Comment by Roemer** [comment]
> I was able to see any of my Swing components (buttons, checkboxes, radio buttons, edit boxes, etc...) with Ranorex Spy, but I think White not recognize the component. Is there anything I need to do or download to make this work?
You can see the elements with Ranorex Spy because it uses various methods to "inspect" an application. White only supports the Microsoft UI Automation Framework.

**Comment by juste3alfaza** [comment]
gaip : ur code doesn't work
Roemer : So any solution to code an C# automation for JAVA app?

**Comment by gaip** [comment]
it should give you an idea how to do using Automation Framework, with copy
and paste, doesn`t work

2015-11-26 14:50 GMT+01:00 juste3alfaza <notifications@github.com>:

**Comment by juste3alfaza** [comment]
gaip : I will see it, but it looks no code can help with JAVA app

**Comment by gaip** [comment]
you are on the wrong direction, Automation element is to use while using
White that means, you have to Support the Frameworks for Automation in
conclusion:

1) Setup the app under test so that you can use the Automation Framework
2) create the code so that you can use the Automation Framework for testing


if not there is not a benefit to use White... if understood right, you have
ranorex so use that.. is also a great tool..


TestStack.White

White is a framework for automating rich client applications based on
Win32, WinForms, WPF, Silverlight and SWT (Java) platforms. It is .NET
based and does not require the use of any proprietary scripting languages.
Tests/automation programs using White can be written with whatever *.NET
language, IDE and tools you are already using. White provides a consistent
object-oriented API, hiding the complexity of Microsoft's UIAutomation
library (on which White is based) and windows Messages.*

**Comment by juste3alfaza** [comment]
ok I see, I am new for automation

**Comment by Roemer** [comment]
Closing since everything about this is already said :)
