### ISSUE TITLE
Searching for a window by a scrap of the name

### ISSUE THREAD

**Issue by plMaybe** [TestStack/White#341]
Hi, 

I’d like to test the application which main window is named with following pattern: [AppName ver. 10.0.0.XXX]. Every new build increases the number to a bigger one (no always to the next one). Is it possible to find that window with Application.Get<Window> but using only piece of the name – [AppName ver. 10.0.0]?
One way could be something like this:
> var win = App.GetWindows().Where(e=>e.Name.Contains("AppName ver. 10.0.0"));

 But it doesn't seem to be the best possible way. Is there any buildin function?

**Comment by dpisanu** [comment]
Currently there are no out of the box functions to achieve this.
You basically first have to resolve all Windows belonging to the App and then iterate through them checking the Name Property.

**Comment by maxinfet** [comment]
Is this an application you have the source code for? If it is you could always give the window an automation id and find it by that. Otherwise @dpisanu's solution is the best choice with some changes to teststack.white.

**Comment by plMaybe** [comment]
Yes I can request for an AutomationId property. It looks like the best possible solution for now. Thank you very much.
