### ISSUE TITLE
Migrating to NUnit

### ISSUE THREAD

**Issue by Roemer** [TestStack/White#342]
Hi
Currently the project uses XUnit. Fair enough but I think it makes it more complex than it needs to be for this project. Especially when using the TestExplorer you cannot jup directly to a test, you only jump to the base "Fact". I know this is only the current implementation but to change this, all the unittest bases need to be rewritten and why not migrate to NUnit to make it easier in general?
There's also another issue with XUnit, I very often run into the problem with unloading appdomains:
```
System.CannotUnloadAppDomainException: Error while unloading appdomain. (Exception from HRESULT: 0x80131015)
   at System.AppDomain.Unload(AppDomain domain)
   at Xunit.ExecutorWrapper.Dispose()
   at Xunit.MultiAssemblyTestEnvironment.Unload(TestAssembly assembly)
   at Xunit.ConsoleClient.Program.RunProject(XunitProject project, Boolean teamcity, Boolean appveyor, Boolean silent)
   at Xunit.ConsoleClient.Program.Main(String[] args)
```
I'm currently unsure how to fix this (as far as I know, White does not keep any Threads open, which is usually the case for this).

So what's your oppinion on this? Is a migration to NUnit an option?

**Comment by dpisanu** [comment]
I would second the move to NUnit. Especially if there is going to be a change in maintainers.

**Comment by Roemer** [comment]
So it's 2:0 for NUnit for now. I'll already start with it and prepare some things.

**Comment by maxinfet** [comment]
Yeah that would make getting into this project a lot simpler. I would be really happy to see this change.

**Comment by Roemer** [comment]
I just did some tests with ButtonTest class, here's my proposal for it:
```
[TestFixture(WindowsFramework.WinForms)]
[TestFixture(WindowsFramework.Wpf)]
public class ButtonTests: WhiteUITestBase
{
	public ButtonTests(WindowsFramework framework)
		: base(framework) { }

	[Test]
	public void Click()
	{
		RunTestTakingFailingScreenshot(() =>
		{
			var button = MainWindow.Get<Button>("ButtonWithTooltip");
			button.Click();
			Assert.That(button.Text, Is.EqualTo("Button Clicked with Mouse"));
		});
	}

	[Test]
	public void ThrowsWhenNotFound()
	{
		RunTestTakingFailingScreenshot(() =>
		{
			using (CoreAppXmlConfiguration.Instance.ApplyTemporarySetting(c => c.FindWindowTimeout = 500))
			{
				Assert.That(() => { MainWindow.Get<Button>(SearchCriteria.ByAutomationId("foo")); },
					Throws.TypeOf<AutomationException>().With.
					Message.EqualTo("Failed to get (ControlType=button or ControlType=check box),AutomationId=foo"));

			}
		});
	}

	[Test]
	public void RaiseClickEvent()
	{
		RunTestTakingFailingScreenshot(() =>
		{
			var button = MainWindow.Get<Button>("ButtonWithTooltip");
			button.RaiseClickEvent();
			Assert.That(button.Text, Is.EqualTo("Clicked"));
		});
	}
}
```
The abstract base class (WhiteUITestBase) is quite similar to the current one, it opens the app on OneTimeSetup and Disposes it at the end. The RunTestTakingFailingScreenshot can be used to collect a screenshot when the test-action fails.
The Arguments in the TestFixture allow to run all tests for different frameworks.
Any feedback on this?

**Comment by maxinfet** [comment]
I think that looks pretty good, particularly the resulting changes to the contents of the test explorer. I don't like the duplication on the RunTestTakingFailingScreenshot but that's pretty minor.

**Comment by dpisanu** [comment]
Any chance to make a seperate branch so we can work on parallel on it?

**Comment by Roemer** [comment]
> Any chance to make a seperate branch so we can work on parallel on it?
That is the plan yes, but I'd like to have some feedback from the "old" crew first.

**Comment by Roemer** [comment]
> I don't like the duplication on the RunTestTakingFailingScreenshot but that's pretty minor.

We can get rid of that :) By using the TestContext and the TearDown attribute.
Looks like this:
```
[TearDown]
public void TestTeardown()
{
	if (TestContext.CurrentContext.Result.Outcome.Status == TestStatus.Failed)
	{
		TakeScreenshot(TestContext.CurrentContext.Test.FullName);
	}
}
```
Now the only thing unsecured is if the test runs into an unexpected exception, but I think that should be handled manually by the writer of the test.

**Comment by maxinfet** [comment]
@Roemer Yeah that looks good to me. I agree with the manual handling by the author.

**Comment by Roemer** [comment]
I also modified the ControlTypeProperty.cs DisplayValue from LocalizedControlType to ProgrammaticName.Split(new[] { '.' }, 2).Last(). This makes the error texts always in english and therefore easier to test in other languages. The downside is, that this is a breaking change (button is now Button, check box is now CheckBox). As alternative, we could dynamically use the strings from for example ControlType.Button.LocalizedControlType. Not sure what's better.

**Comment by Roemer** [comment]
I guess I go with the 2nd approach. Tests then should look like this:
```
Assert.That(() => { MainWindow.Get<Button>(SearchCriteria.ByAutomationId("foo")); },
	Throws.TypeOf<AutomationException>().With.
	Message.EqualTo(String.Format("Failed to get (ControlType={0} or ControlType={1}),AutomationId=foo",
		ControlType.Button.LocalizedControlType, ControlType.CheckBox.LocalizedControlType)));
```

**Comment by Roemer** [comment]
Just to let you know, I just startet a new nunit branch: https://github.com/TestStack/White/tree/nunit
The TestStack.White.UnitTests are fairly straight forward to migrate, for the TestStack.White.UITests, I created the WhiteUITestBase and migrated the ControlTests/ButtonTests.cs. Feel free to continue migration!

**Comment by maxinfet** [comment]
Awesome, I will be taking a look at that as soon as I get home

**Comment by Roemer** [comment]
I hope we can get this thru quickly, then we can enable the appveyor build and have a fully functional CI :)

**Comment by Roemer** [comment]
I just migrated some more. This should give you a start to continue. I'll also continue later.

**Comment by JakeGinnivan** [comment]
Looks good, awesome to see stuff happening, should have invited people earlier :P The changes you are making would make xUnit nicer as well, the issue is the patterns I have used (base class with the test then abstract methods) instead of composition. The test fixture attiribute is quite nice, doing that with XUnit would be a little clunky I think. Generally though I have been moving most my projects to XUnit because it encourages better structured tests and more idiomatic .net code. The attributes for setup and teardown are really odd and sharing class instances across tests ends up being painful.

The other thing is look into Shouldy for assertions, with Shouldly `Assert.That(button.Text, Is.EqualTo("Clicked"));` becomes `button.Text.ShouldBe("Clicked");` and if it fails the error message contains the code before the `Should` method. i.e `button.Test should be "Clicked" but was "Not Clicked"`

**Comment by Roemer** [comment]
Progress is good so far :)
:x: 14 Tests Failed
:warning: 12 Tests Skipped
:white_check_mark: 180 Tests Passed

But still quite some tests to migrate. If someone wants to jump in, Start at the bottom uf the White.UITests or White.UnitTests and check-in very often! And look at the already migrated files, so that the style is the same.

**Comment by maxinfet** [comment]
I will be jumping in but would you be willing to look at some of my previous pull request before I start merging anything? I am very new to git and I am not familiar with the workflow. I would just like to know if I need to do anything different with my pull request before I do a lot more.

**Comment by maxinfet** [comment]
Also when running the test it will build WpfTodo and Todo.Core. These contain a version of fody that is not compatable with VS2015. I upgraded it in one of my pull request (https://github.com/TestStack/White/pull/300). I dont know what the consequences of this upgrade are other then I can compile those projects in VS2015. Does anyone here have enough knowledge about fody to know if those upgrades are ok? If its ok I will create a seperate pull for TestStack.White proper so its not just in the UIComWrapper branches.

**Comment by Roemer** [comment]
As for your first question:
Best would be to clone the nunit branch completely fresh and work on this one directly.

**Comment by maxinfet** [comment]
Thanks for looking over my pull requests

**Comment by Roemer** [comment]
Here are some regex search/replace I use to migrate a big part of old tests:
```
Assert.Equal\(true,(.*)\)
Assert.That($1, Is.True)

Assert.True\((.*)\)
Assert.That($1, Is.True)

Assert.Equal\(false,(.*)\)
Assert.That($1, Is.False)

Assert.False\((.*)\)
Assert.That($1, Is.False)

Assert.Equal\((.*), (.*).Count\);
Assert.That($2, Has.Count.EqualTo($1));

Assert.Equal\((.*), (.*)\)
Assert.That($2, Is.EqualTo($1))

Assert.NotNull\((.*)\)
Assert.That($1, Is.Not.Null)

Assert.Null\((.*)\)
Assert.That($1, Is.Null)
```

**Comment by maxinfet** [comment]
Thanks, that will help quite a bit

**Comment by mwhelan** [comment]
Just to add to what @JakeGinnivan said. A good assertion framework like Shouldly is worth considering, not just because it improves the readability of the tests - which it does - but also because of how much it improves the error messages and makes it much easier to work out why a test is failing. Also, it means you are not tied to the testing framework, so if you were to change testing frameworks again in the future none of your assertions would be affected.

**Comment by Roemer** [comment]
New stats:
:x: 26 Tests Failed
:warning: 22 Tests Skipped
:white_check_mark: 359 Tests Passed

**Comment by Roemer** [comment]
Just ran the first "no-so-bad" build on appveyor: https://ci.appveyor.com/project/RomanBaeriswyl/white-9yaco
Guess we have that pretty soon! About Shouldly: that is still on the list to look at. Probably only a regex search/replace at the end when we unified all tests.

**Comment by Roemer** [comment]
I just created the pull request https://github.com/TestStack/White/pull/348, please have a look at it!
