### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by JakeGinnivan** [TestStack/White#352]
With the increased activity, one of the things on the top of my todo list if I got back to White was to sort out documentation.

I am using readthedocs.org for my other projects. The reason for this is that all docs live inside the `/docs` folder in your repo, whenever master moves on it will build the latest docs. When you tag the repo it will snapshot the docs for that version. The docs are just written in markdown.

An example of this is http://gitversion.readthedocs.org/en/latest/.  and the source is https://github.com/GitTools/GitVersion/tree/master/docs

I am more than happy to set this up for white if you guys think it's a good approach. Once it is set up you guys can drive the migration of old docs and adding of new docs. I think this is critical to get going if you are going to get White back up with a good community.

**Comment by maxinfet** [comment]
I would like to see this happen. I like the idea of the documentation living in the repository.

**Comment by JakeGinnivan** [comment]
Done.

http://teststackwhite.readthedocs.org/en/latest

It would be great to see activity around the docs now.

**Comment by JakeGinnivan** [comment]
Have added the docs badge to the readme too
