### ISSUE TITLE
Facing problem with ListView

### ISSUE THREAD

**Issue by vivek9591** [TestStack/White#365]
Hi,
Can you help me out how to get element present in ListView based on Button text on WPF screen.
I tried to find it but its not detecting any element present in ListView. (using white framework)

Thanks in advance!

**Comment by maxinfet** [comment]
Can you provide a screen shot of the list views hierarchy?

**Comment by vivek9591** [comment]
Hi @maxinfet 
Please, find the screen shot attached.
Thanks!
![capture](https://cloud.githubusercontent.com/assets/10534367/12163466/eb2772a0-b533-11e5-9be6-9134a313b34f.JPG)

**Comment by Roemer** [comment]
To me it looks like the Text on the buttons is not a real text and just painted onto the button. Is this control open source so that we can have a better look at it?

**Comment by dpisanu** [comment]
actually it looks like a Text inside the Button.
So basecally he would have to iterate over all the buttons, find the included Text Control and check for the Value.

**Comment by Roemer** [comment]
True. Looked at it too quickly (missed the "Open" text). So each "button" element consists of multiple elements (image, text with another nested text). And those two text elements contain the text you're looking for.
So do as @dpisanu proposed:
* Loop thru each button
  * Get the text element from the button
  * Compare the text of this element to your wanted one
  * If it is the wanted one, you found the button you want
  * If not, continue with the next button

For performance reason, you could do this once for all buttons and save them in a dictionary or something.

**Comment by vivek9591** [comment]
Its text inside the button.

**Comment by vivek9591** [comment]
Yes @Roemer @dpisanu 
You are right, each "button" element consists of multiple elements (image, text with another nested text).
Can you give some hint(sample) as I am very new to white framework.

**Comment by Roemer** [comment]
For now I haven't found a way to search for childen on a button except by using the raw automation.
Here's an example:
```
private Button FindButton(IEnumerable<Button> buttons, string wantedText)
{
    foreach (var button in buttons)
    {
        var finder = new AutomationElementFinder(button.AutomationElement);
        var children = finder.Children(AutomationSearchCondition.ByControlType(ControlType.Text));
        if (children.Count == 1)
        {
            var text = new Label(children[0], button.ActionListener);
            if (text != null)
            {
                var buttonText = text.Text;
                if (buttonText == wantedText)
                {
                    return button;
                }
            }
        }
    }
    return null;
}
```
Where the buttons passed into this method could be read like this:
```
var application = Application.Launch(yourAppPath);
var window = application.GetWindow(yourWindowTitle);
var buttons = window.GetMultiple(SearchCriteria.ByControlType(ControlType.Button)).OfType<Button>();
```

**Comment by maxinfet** [comment]
We should really add a AutomationElementFinder to every control so we don't have to drop down to raw automation to find children of a control. Controls like TreeItem already have them and it seems like we could just put it on UIItem.

**Comment by Roemer** [comment]
Found a better way for WPF:
If you add ```using TestStack.White.UIItems.WPFUIItems;```
You can use it's extension methods and do it like this:
```csharp
private static Button FindButton(IEnumerable<Button> buttons, string wantedText)
{
    foreach (var button in buttons)
    {
        if (button.Framework == WindowsFramework.Wpf)
        {
            if (button.Exists<Label>(SearchCriteria.ByControlType(ControlType.Text)))
            {
                var text = button.Get<Label>(SearchCriteria.ByControlType(ControlType.Text));
                if (text != null)
                {
                    var buttonText = text.Text;
                    if (buttonText == wantedText)
                    {
                        return button;
                    }
                }
            }
        }
    }
    return null;
}
```
Note: The "Exists" extension method was just added.

**Comment by dpisanu** [comment]
I am just gonna put in pseudo code for you.

```javascript
Button locatedButton = null;
var list = Window.Get(SearchCriteria_For_List);
foreach(var listItem in list.Items)
{
   var button = listItem.Get(SearchCriteria_For_Button);
   if (button == null) contiue;
   // Text is of Type TestStack.White.UIItems.Label
   var text = button.Get(SearchCriteria_For_Text);
   if (text == null) continue;
   if (text.Value != "The Text I am looking for") continue;

   locatedButton = button;
   break;
}

foundButton.Click();
```

This can be optimized quite a bit but should give you the step by step idea of how to drill down through the whole structure.

**Comment by vivek9591** [comment]
Thanks @Roemer ,
Your code is working fine.
And thanks everyone for your response.

**Comment by dpisanu** [comment]
If your Test is not time critical then doing an Exist and then a Get is ok.
But keep in mind that this does the Lookup operation twice.

I see the Exists as more of a check functionality if you just want to know if an element for a certain criteria is available but you do not need to work with it.
If you actually need to work with the item I would then directly do a Get and handle the Exception in the test.

Roemer mentioned he has planned to implement a TryGet.
I see this as a gracefull Get call that does not throw you an exception but will handle them internally and just return NULL in case the Lookup failed or turns out empty handed.
This would shorten down to a simple NULL check in the test code.

**Comment by Roemer** [comment]
So can this be closed?
