### ISSUE TITLE
White.Core.UIItems.UIActionException: Window didn't respond... ---> System.ComponentModel.Win32Exception: Access is denied.

### ISSUE THREAD

**Issue by jalla347** [TestStack/White#37]
I keep getting this:
White.Core.UIItems.UIActionException: White.Core.UIItems.UIActionException: Window didn't respond, after waiting for 10000 ms ---> System.ComponentModel.Win32Exception: Access is denied.

System.Diagnostics.ProcessManager.OpenProcess(Int32 processId, Int32 access, Boolean throwIfExited)
System.Diagnostics.Process.GetProcessHandle(Int32 access, Boolean throwIfExited)
System.Diagnostics.Process.WaitForInputIdle(Int32 milliseconds)
System.Diagnostics.Process.WaitForInputIdle()
White.Core.UIItems.WindowItems.Window.WaitForProcess()
White.Core.UIItems.WindowItems.Window.WaitWhileBusy()
White.Core.UIItems.WindowItems.Window.WaitWhileBusy()
White.Core.UIItems.Actions.Action.Handle(Window window)
White.Core.UIItems.WindowItems.Window.ActionPerformed(Action action)
White.Core.InputDevices.Mouse.ActionPerformed(ActionListener actionListener)
White.Core.InputDevices.Mouse.Click(Point point, ActionListener actionListener)
White.Core.UIItems.UIItem.PerformClick()
White.Core.UIItems.UIItem.PerformIfValid(Action action)
White.Core.UIItems.UIItem.Click()

I get this when I click on a menu item that exit the application. According to http://white.codeplex.com/discussions/80049 the problem is that the clicking trigers ActionPerformed to be run which will wait for the application to be not idle. However, the application will at some point exit, and the WaitForInputIdle will fail because it waits for an application that does not exist.

Anyone else experiencing this problem? I have two automated test servers. One of them gives me this all the time, but the other one does not. The one with the problem runs Windows Server 2003 and has a single processor (I think), and the other has dual processor and Windows Server 2008.

**Comment by krithi82** [comment]
Hi,

I am facing similar issue now. Getting the same error message after inputting a number on the window. Actually, the window changes after input. Can someone help me please?
