### ISSUE TITLE
How to generate report in HTML format using white framework?

### ISSUE THREAD

**Issue by vivek9591** [TestStack/White#374]
Hi,

I am using white framework to automate WPF application and NUnit for reporting. But I want the report in HTML format. Is there any way to generate report in HTML format using white framework. If possible  please let me know.

Thanks in advance!

**Comment by dpisanu** [comment]
What kind of report are you looking for?
White is an Automation Framework and not a reporting Framework.

Have a look at ReportUnit which is a Tool that takes the Unit Test Logfiles and creates a HTML Report out of it.
http://relevantcodes.com/reportunit-report-generator/

**Comment by vivek9591** [comment]
Thanks @dpisanu 
I will go through ReportUnit tool.
