### ISSUE TITLE
How do i get a sibling element?

### ISSUE THREAD

**Issue by kappa10j** [TestStack/White#398]
I have a label control who's next sibling element is a combobox I'm looking for.  There is no id so i need to do it this way.  Is there any get sibling method?

**Comment by kappa10j** [comment]
I created 2 extension methods that i'd like to contribute to the project.

        public static T GetNextSibling<T>(this IUIItem thisItem) where T : IUIItem
        {
            var parent = TreeWalker.ControlViewWalker.GetNextSibling(thisItem.AutomationElement);
            var uiItem = new DictionaryMappedItemFactory().Create(parent, thisItem.ActionListener);
            return (T) UIItemProxyFactory.Create(uiItem, uiItem.ActionListener);
        }

        public static T GetPreviousSibling<T>(this IUIItem thisItem) where T : IUIItem
        {
            var parent = TreeWalker.ControlViewWalker.GetPreviousSibling(thisItem.AutomationElement);
            var uiItem = new DictionaryMappedItemFactory().Create(parent, thisItem.ActionListener);
            return (T) UIItemProxyFactory.Create(uiItem, uiItem.ActionListener);
        }

**Comment by guigasparotto** [comment]
This is great!!! Thanks!!!
