### ISSUE TITLE
How to verify if something is drawn on the Canvas?

### ISSUE THREAD

**Issue by vivek9591** [TestStack/White#419]
Hi,
Actually, my application is developed mainly for giving presentation. That's means you can perform write operation on it.

But my question is, if something is drawn on canvas then **how to verify it whether it drawn or not** in automation.

Please help me!!

Thanks in advance!!

**Comment by dpisanu** [comment]
I am unsure right now if drawings inside a canvas can even be automated.
This is a purely rendering side implementation and not a UI Control that is being displayed.

**Comment by eidermauricio** [comment]
Yes finding the expected image inside screenshot. Following technique goes beyond of White and might help you:

1) lf you know the exact drawed image in your canvas (i.e. saving a small cropped bitmap screenshot of the rendered boundaries), lets call it as the expected image which needs to be stored in a file or project resource.

2)  For finding pattern (rendered image into canvas) Take an screenshot in bitmap format also.

3) Find target image inside screenshot taken in step 2. To do so you must use this method 
private Rectangle searchBitmap(Bitmap smallBmp, Bitmap bigBmp, double tolerance) see this 

http://www.codeproject.com/KB/graphics/BitmapDetector.aspx?fid=1544671&df=90&mpp=50&noise=3&sort=Position&view=Quick


Thats all

**Comment by vivek9591** [comment]
Thanks @eidermauricio,
For your reply. Actually, currently I am using image comparison but screenshots vary in size. Like first time suppose size is 1 kb then second time size change to 1.2 kb something like this. So, comparison is going to fail. That is the big problem I am facing.

But thanks a lot for your good answer.

**Comment by dpisanu** [comment]
Comparing images is a real pain. Do not compare file sizes.
At least do a pixel comparison but that is tedious work. Different image sizes due to resolution changes and so forth make it ugly. But there is alot of code example on the web for it.

https://thecsharper.com/?p=94

There is also a method to scale images down to the lowest common size and then do some image magic trickery on it. it's fast, it gives damn good results. I am just looking for it right now.

**Comment by vivek9591** [comment]
Thanks @dpisanu ,

Currently, I am using the following project. This is also open source. Please, have a look.

[http://www.codeproject.com/Articles/374386/Simple-image-comparison-in-NET](url)

**Comment by dpisanu** [comment]
Ok, I found it again.
I was thinking of ImgHash.
Have a look at this here. http://www.hackerfactor.com/blog/?/archives/432-Looks-Like-It.html

There are some implementations available in C, C++ and C# here in GitHub.
For Example: https://github.com/cybergeek94/ImgDup.Net

**Comment by vivek9591** [comment]
Yes done
Thank you!!
