### ISSUE TITLE
White is taking long time when there is no alerts

### ISSUE THREAD

**Issue by Chandru1210** [TestStack/White#422]
Hi,

in my GUI some times I'm getting alerts but not getting all the times so I used try... catch method but white is taking long time when there is no alerts. how can I fix the time limit in this scenario... ?please assist me.

Thanks in advance,
Chandru.

**Comment by dpisanu** [comment]
How are the alerts being displayed. Is it a Modal Window or some Control in the Application that shows a blocking message that first needs to be removed?

In case of a Modal Window, you can always check for Window.ModalWindows().Any().
In the case that some control locks the UI and first needs to be ticked off or something, you will need to go the road you are already walking on. 
Either frequently check for the error case or only check the error case if the control you want to automate does not react.
Either way, it's not an ideal situation since you are polling all the time. You can lower the timeout value of white but that will not guarantee you a better performance and a better result.

**Comment by Chandru1210** [comment]
in this case it won't take more than 5 seconds to pop up the alerts. so need to fix the time limit. if I get all the alerts then it won't take much time. if not getting white still searching the alert control so I just want to fix that searching limit. please help me to fix it.

**Comment by dpisanu** [comment]
I am not going to be able to fix your code but give you some advice and pointers.
Try playing around with "TestStack.White.Configuration.CoreAppXmlConfiguration"
Here you can configure the Timeouts for White.

For Example: 
,,,
            CoreAppXmlConfiguration.Instance.BusyTimeout = 3;
            CoreAppXmlConfiguration.Instance.FindWindowTimeout = 3;
            CoreAppXmlConfiguration.Instance.UIAutomationZeroWindowBugTimeout = 3;
            CoreAppXmlConfiguration.Instance.PopupTimeout = 3;
            CoreAppXmlConfiguration.Instance.TooltipWaitTime = 3;
            CoreAppXmlConfiguration.Instance.SuggestionListTimeout = 3;
            CoreAppXmlConfiguration.Instance.HighlightTimeout = 3;
,,,

**Comment by Chandru1210** [comment]
here is my code
try
                {
                    TestStack.White.UIItems.Button alert1= mainWindow.Get<TestStack.White.UIItems.Button>(SearchCriteria.ByAutomationId("2"));
                    alert1.Click();
                }
                catch(TestStack.White.AutomationException)
                {
                    Console.WriteLine("No Automation Alerts received");
                }
instead of using try catch have to fix time limit..

**Comment by dpisanu** [comment]
Your try catch is expensive. 
It assumes it locates the button and then clicks on it. Any of the two operations can cause an exception.

Is your Application done in WPF?
Have a look at TestStack.White.UIItems.WPFUIItems.WPFUIItem
There you will find a function called "Exists" that returns a bool.
This ought to cut down the expensive and iffy try catch.

The function itself is time expensive as well though.

**Comment by Chandru1210** [comment]
Sorry... no luck.

i tried with the below but not able to fix also not found the "Exists" function

if (TestStack.White.UIItems.WPFUIItems.WPFUIItem.Get(mainWindow, SearchCriteria.ByAutomationId("6")).Visible == true)
                {
                   TestStack.White.UIItems.WPFUIItems.WPFUIItem.Get(mainWindow, SearchCriteria.ByAutomationId("6")).Click();
                }

**Comment by dpisanu** [comment]
You need to include the following line along to the exisit usings.

using TestStack.White.UIItems.WPFUIItems;

Then you can access the extention methods in the WPFUIItem class.
Problem again with your approach is you rely on the button to be available. I do not know your application but if the button is only present on error cases, you will first need to check if it exists.
Calling Visible == true on it might result in a NullReferenceException if whote does not find the button.

**Comment by Chandru1210** [comment]
thanks Dannie. it's working
