### ISSUE TITLE
How to perform touch operation if mouse is not available for the touch device?

### ISSUE THREAD

**Issue by vivek9591** [TestStack/White#423]
Hi, 

Currently, I am using mouse operation to perform click and draw operation.
Suppose, same thing we are performing on touch device and mouse is not available then how to perform click operation and line draw operation. 

Please suggest me some good idea.

Thanks in advance!!

**Comment by dpisanu** [comment]
Please correct me if I am wrong but Touch is just another HID layer ontop of the Mouse.
So even if you have no mouse and keyboard connected to your device, using the White Layers for these HID components should still work.

**Comment by vivek9591** [comment]
Yes, you are correct. Is it possible to use touch events instead of mouse events.
How to automate by taking two point to draw a line on canvas using touch events.
For mouse events the code is as follow:
`Cursor.Position = new System.Drawing.Point(300, 200);
            mouse_event((int)(MouseEventFlags.LeftDown), 0, 0, 0, 0);
            Cursor.Position = new System.Drawing.Point(400, 200);
            mouse_event((int)(MouseEventFlags.LeftUp), 0, 0, 0, 0);.`

**Comment by dpisanu** [comment]
Take a look at the White Mouse class.
It pretty much just wraps the Win32 stuff into a more manageable api.

```javascript

TestStack.White.InputDevices.Mouse.Location = new Point(x,y);
TestStack.White.InputDevices.Mouse.LeftDown();

const int stepLength = 10;
Point targetPoint = new Point(x,y);

var startPosition = TestStack.White.InputDevices.Mouse.Location;
double distanceX = targetPoint.X - startPosition.X;
double distanceY = targetPoint.Y - startPosition.Y;

double distance = Math.Sqrt(Math.Pow(distanceX, 2) + Math.Pow(distanceY, 2));
double stepCount = Math.Ceiling(distance / stepLength);
double stepLengthX = distanceX / stepCount;
double stepLengthY = distanceY / stepCount;

double currentX = startPosition.X;
double currentY = startPosition.Y;
for (int i = 0; i < stepCount; i++)
{
   currentX += stepLengthX;
   currentY += stepLengthY;

   TestStack.White.InputDevices.Mouse.Location = new Point((int)currentX, (int)currentY);
   Thread.Sleep(5);
}
```

**Comment by Roemer** [comment]
I think if you really need real touch support, you need to use https://msdn.microsoft.com/en-us/library/windows/desktop/hh802881(v=vs.85).aspx (InjectTouchInput). There are some wrappers for .Net around, white does not support it directly currently.

**Comment by vivek9591** [comment]
Ok thanks!!
