### ISSUE TITLE
How to copy invoke method functionality from Visual UI Automation?

### ISSUE THREAD

**Issue by shrapnelstudios** [TestStack/White#426]
I have a Save button that is nested in a tool bar, in a pane, inside another pane. Another strange thing about it is that the control is not actually a button, but an enumeration. Don't ask me, I'm just the automation guy lol.

Anyways, when i use button.Click() or button.RaiseClickEvent() on the button, it does seem to click the save button, however, the information that i entered does not save.

If I open Visual UI Automation Verify and use the invoke method, the save button actually clicks AND saves the data.

so my question is, how do i write the code so that it does the same thing as clicking invoke method from Visual UIA?

![image](https://cloud.githubusercontent.com/assets/18513924/15504170/a6cee72c-218b-11e6-82ec-f6524aae97a5.png)

**Comment by dpisanu** [comment]
```javascript
var pattern = button.AutomationElement.GetCurrentPattern(InvokePattern.Pattern);
var invokePattern = pattern as System.Windows.Automation.InvokePattern;
invokePattern .Invoke();
```

**Comment by dpisanu** [comment]
I tend to prefer the Invoke Pattern over Click for Buttons. It is alot
faster and less error prone.
On the other hand though it circumvents possible artificial ui restrictions
imposed by view hackery.

For example the Application creates an opaque overlay over the button.
A user driven interaction via Click wont work anymore but the InvokePattern
still comes through.
There are a few such examples when working with automation frameworks where
some access points to a control actually bypass custom view code.
TextBox is another good example.
Am 24.05.2016 14:44 schrieb "shrapnelstudios" <notifications@github.com>:

**Comment by shrapnelstudios** [comment]
Thanks your your replies dpisanu. I used the code you provided above and it is working just like the button.click command... the button gets clicked, but the data does not save.

Im not sure how to solve this issue. When i make Visual UI Automation click the button, it saves the data correctly.

**Comment by dpisanu** [comment]
What you can do it use TestStack.White.InputDevices.Mouse.
Set it to some location inside the Button.Bounds and then do a Mouse Click.
See how that behaves for you.
