### ISSUE TITLE
Application.cs not found

### ISSUE THREAD

**Issue by carloszuccarini** [TestStack/White#436]
Hello,
I'm new with White and I recently fell into this error that I don't understand.

Code:
var processStartInfo = new ProcessStartInfo(KSS_ExeSourceFile);
var KSS_Application = TestStack.White.Application.AttachOrLaunch(processStartInfo);

Error while debugging:
Application.cs not found
You need to find Application.cs to view the source for the current call stack frame

Source search information
Locating source for 'c:\TeamCity\buildAgent\work\89a20b30302799e\src\TestStack.White\Application.cs'. Checksum: MD5 {35 7 ac bc 69 ee f0 45 f3 39 2 67 7b 6d f7 5f}
The file 'c:\TeamCity\buildAgent\work\89a20b30302799e\src\TestStack.White\Application.cs' does not exist.
Looking in script documents for 'c:\TeamCity\buildAgent\work\89a20b30302799e\src\TestStack.White\Application.cs'...
Looking in the projects for 'c:\TeamCity\buildAgent\work\89a20b30302799e\src\TestStack.White\Application.cs'.
The file was not found in a project.
Looking in directory 'C:\Program Files (x86)\VC\crt\src\'...
Looking in directory 'C:\Program Files (x86)\VC\crt\src\vccorlib\'...
Looking in directory 'C:\Program Files (x86)\VC\atlmfc\src\mfc\'...
Looking in directory 'C:\Program Files (x86)\VC\atlmfc\src\atl\'...
Looking in directory 'C:\Program Files (x86)\VC\atlmfc\include'...
The debug source files settings for the active solution indicate that the debugger will not ask the user to find the file: c:\TeamCity\buildAgent\work\89a20b30302799e\src\TestStack.White\Application.cs.
The debugger could not locate the source file 'c:\TeamCity\buildAgent\work\89a20b30302799e\src\TestStack.White\Application.cs'.

Would you help? 
I removed the package and installed again, the same.
Also, I ran the .NET fixer, still no luck.

Thanks

**Comment by dpisanu** [comment]
how exactly are you including White in your project?
Via the NuGet package, DLL or Project Reference?

**Comment by maxinfet** [comment]
I would have expected a exception message with the error you are describing. Normally when an exception is thrown while you are debugging over third party code it will ask you to load the file or symbols if you have them and tell you what type of exception was thrown. If you have any information about the type of exception I would be interested in knowing.

**Comment by Roemer** [comment]
Closed due to inactivity
