### ISSUE TITLE
Can not get the DevExpress control by AutomationId or Name

### ISSUE THREAD

**Issue by eightrivers** [TestStack/White#437]
We used some DevExpress controls in a winform based application, such as EditBox and DateTimeEditor. Seems we can not get those controls by AutomationId or Name, because the AutomationId  is always a randomly number and the name is empty. 

We checked the other threads and understand that it is not the case that White need to be responsible for. But we still want to know whether there is one of preview release of White, which can give a workaround for this issue. 

Thanks!

**Comment by maslisko** [comment]
I guess there is no such version of White, since it is technically impossible. You will probably need to use a different method of searching for such items (you might, for example, be able to get the parent node of the automation tree and get the button as n-th child of a specific control type/class/etc.)

**Comment by eightrivers** [comment]
@maslisko Got it. Thanks for your kindly reply. We will try to find another to step out from this issue. Thanks.

**Comment by FeedHedgehog** [comment]
@eightrivers  hey,did you find the way to fix the bugs?I have been through the same thing ever you did.can u tell me how to fix this,if given some examples,I will be much appreciate.

**Comment by eightrivers** [comment]
@FeedHedgehog not yet, seems this issue can not be fixed without the help or support from devexpress, so we make a workaround for it. That is not to use the automation id or name of the input control, but use the label nearby the input control. for example, title="First Name", type ="TextBox" means trying to find a textbox, which is nearest textbox to the label which's text is "First Name "

Hope it can help you.

**Comment by FeedHedgehog** [comment]
@eightrivers  Thanks  a lot,I see.I am working on a WPF project now,that can fits Whie very well.
