### ISSUE TITLE
Grid as UIItemContainer

### ISSUE THREAD

**Issue by Edimz** [TestStack/White#444]
Hi there, I have a grid in my application for which I need to find some UIItems within, is there a more abstract container-like class I could use for this purpose? I can't find any useful class in White.

**Comment by Edimz** [comment]
This is how my UI is built essentially:

```
<MainWindow>
   <Grid id=G1>
      <Button id=B1/>
   </Grid>
   <Grid id=G2>
      <Button id=B1/>
   </Grid>
</MainWindow>

```
So the problem is that I need to look inside a grid, but there is no UIItem that is similar to a grid, can I somehow use UIItemContainer istead? Like so:

```
UIItemContainer container = Window.Get<UIItemContainer>(SearchCriteria.ByAutomationID("G1"));
Button button = container.Get<Button>(SearchCriteria.ByAutomationID("B1"));

```
So, this is how I could like it to be =) Simple and easy to use.

**Comment by maxinfet** [comment]
I built a test application to attempt to look for a solution to this problem but after putting this form together I wasn't able to see the grids with UIAVerify or Inspect. Do you have some example code that I could take a look at this problem in?

    <Window x:Class="Issue444.MainWindow"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        mc:Ignorable="d"
        AutomationProperties.AutomationId="Issue444"
        Title="MainWindow" Height="84.911" Width="101.479">
    <Grid>
        <Grid AutomationProperties.AutomationId="Grid1" HorizontalAlignment="Left">
            <Button Name="Button1" Content="Button1" Click="Button1_Click"/>
        </Grid>
        <Grid AutomationProperties.AutomationId="Grid2" HorizontalAlignment="Right">
            <Button Name="Button2" Content="Button2" Click="Button2_Click"/>
        </Grid>
    </Grid>
</Window>

**Comment by Edimz** [comment]
Try using Snoop 2.8.0, it is a very good ui inspection tool. From there I can find all ui items including grids. Maybe grids don't count as ui item and that why other programs can't find it?

I think your application would work, my companys app is way more complex but essensially its the same logic for this issue.

**Comment by maxinfet** [comment]
Snoop shows many elements which can only be accessed as part of the visual tree. UIAs tree view differs from the visual tree and has a lot less elements in it. Use inspect or UIAVerify to see what UIA is actually able to interact with.
