### ISSUE TITLE
Unable to control the dialog

### ISSUE THREAD

**Issue by Chandru1210** [TestStack/White#454]
Hi,

i'm trying to automate the refresh data in add- on excel file. when i clicking on the refresh option the add-on macro throwing the dialog to enter the user credentials but am not able to control this dialog box. please assist that how to control this dialog box.

![image](https://cloud.githubusercontent.com/assets/18435049/16771645/e24f29e2-486e-11e6-85ab-1a196b63b7fc.png)

**Comment by Chandru1210** [comment]
i addressed that it is a new window but unable to access the controls like button,text box,.... can you please help me on how to access the controls in new window from main window

**Comment by ivan-danilov** [comment]
Can you see the controls you need in tools like VisualUIAVerify or Inspect?
Judging by the look you have pretty old UI there. It might be the case that it doesn't yet support UIAutomation properly. You may have some luck with MSAA (I believe it should be exposed in UIA through LegacyIAccessible pattern), but I'm not sure in it either. Need to check.

**Comment by Chandru1210** [comment]
yes i can see the controls. here i attached the screenshot with automation id for text box but still not able to access this control.

![image](https://cloud.githubusercontent.com/assets/18435049/16800118/44b8cd5c-4911-11e6-88c6-b05111041d79.png)

![image](https://cloud.githubusercontent.com/assets/18435049/16800134/5e2526b4-4911-11e6-999f-29c276c72ea9.png)

**Comment by Chandru1210** [comment]
Issue solved

**Comment by Shunmugapriyansp** [comment]
Chandru , Were you able to handle the dialog? if yes, how did you manage to do?
