### ISSUE TITLE
Can I Record User Input

### ISSUE THREAD

**Issue by DotNetRockStar** [TestStack/White#458]
Hey there.  I'm not 100% sure where this question goes, but I was wondering if there was a way that I can run "something" and record user input and have it generate the code to replay what they just did.  Similar to how Selenium or the Microsoft ui testing suite works.  The reason that I ask this is because I have QA staff that does not write code but it would be great if my QA folks could use this product.

Thanks in advance!

**Comment by maxinfet** [comment]
White does not have the functionality to record user input and play it back.
