### ISSUE TITLE
Close Page Tab

### ISSUE THREAD

**Issue by ManaAutomation** [TestStack/White#461]
Hello,
I have a **mainTab** under this couple of child tabs ,am able to keep focus and select the required tab but facing problem to close that tab,each tab is having **close button** but when i use UI verify tab is getting identified but not '**x**' button. i tried to see childs ,ascendants using treewalker but no luck,

can any one help me how perform close tab action uinsg White/UIACOM Wrapper/UI Automation?
my application:
Windows form,Infragistics controls,

NOTE: here am using TreeWalker ,since using White framework am not able to identify tabs or Grids or menubar or trees. its because my application controls are using 3rd party Infragistics controls.

**Comment by RaviAutomation** [comment]
Can anyone help to find the solution to close the opened tab using treewalker/UIAconwrapper? its blocking my automation.

**Comment by tlbzeu** [comment]
AutomationElement element = parent.GetElement(SearchCriteria searchCriteria);
var clickableElement = element.GetClickablePoint();
Mouse.Instance.Click(clickableElement);

this is how i`ve done it in my situation.

**Comment by ManaAutomation** [comment]
Thanks for your reply, but in my case i have close button on my TABITEM,you can see the attachment and assist the possible solutions.you can find it in red colour.
![cross](https://cloud.githubusercontent.com/assets/1586248/18079776/0e0815aa-6eb0-11e6-9b65-522dfba9183f.png)

**Comment by tlbzeu** [comment]
can u show what UI Spy shows when u focus on x?

**Comment by ManaAutomation** [comment]
I cant focus on X button using either UI SPY or UI Verify and not giving as child/descendant..
![uispy](https://cloud.githubusercontent.com/assets/1586248/18080505/7c3fa5da-6eb3-11e6-83bb-d44a3751b794.png)
![uiverify](https://cloud.githubusercontent.com/assets/1586248/18080506/7c401754-6eb3-11e6-90de-d1e5b011ae96.png)

**Comment by tlbzeu** [comment]
I had something similar and my workaround was something like this:
{
```
// other logic 
//...
var tabItem = parent.Get(SearchCriteria.ByText("Name"));
var rightCorner = tabItem.Bounds.Right.ToString();
var bottomCorner = tabItem.Bounds.Bottom.ToString();
int x = Int32.Parse(rightCorner);
int y = Int32.Parse(bottomCorner);
ClickOnPoint(x, y);
}
public void ClickOnPoint(int x , int y)
{
var clickPoint = new System.Windows.Point(x, y);
Mouse.Instance.Click(MouseButton.Left, pointClick)
}
```
Then add few pixels on both sides till it clicks on .

**Comment by tlbzeu** [comment]
```
var rightCorner = expTabItem.Current.BoundingRectangle.Right.ToString()
var bottombCorner = expTabItem.Current.BoundingRectangle.Bottom.ToString()
int x = Int32.Parse(rightCorner);
int y = Int32.Parse(bottomCorner);
x = x - (few pixels)
y= y + (few pixels)
```

**Comment by ManaAutomation** [comment]
Thank you bro..its working ..after using x=90..but is there any way without passing these x and y co-ordinates
because,if case of interrupts in between running the code ,then it would have been click on any window ,which ever is in-front of the application

**Comment by tlbzeu** [comment]
You already check if you are on the desired element with:
`if (expTabItem.Current.Name.ToLower() == "My Tab Name"){`
I can `t find another solution , and I was searching for another method for like 20 days see: [Link](http://stackoverflow.com/questions/38871001/teststack-white-how-to-click-on-hyperlink-located-in-a-document-in-winform-appli)

**Comment by ManaAutomation** [comment]
Thank you,tlbzeu for your time effort to fix my problem. IsEnabled is always TRUE after and before closing the tab.

**Comment by tlbzeu** [comment]
`if(expTabItem.Current.Name.ToLower() == "My Tab Name" && expTabItem.Current.IsEnabled)`

**Comment by ManaAutomation** [comment]
One more doubt ,we don't have any **IsClosed** method to check that specific tab has been closed or not...is there any alternative way to make sure that tab has got close?

**Comment by tlbzeu** [comment]
I will edit this message in a few minutes, have to present something right now :)

**Comment by ManaAutomation** [comment]
Its really ,cant forget your contribution in order to resolve my issues. yes i have constructed with the help of above code and test piece of code working fine.am planning to compile this with my existing framework and let you know the final status. once again thanks my dude..

**Comment by tlbzeu** [comment]
yw, glad i could help u :)

**Comment by ManaAutomation** [comment]
Thanks for your support,made it easy automation.
