### ISSUE TITLE
Unable to get dll's via nuget package installed via visual studio 2015.

### ISSUE THREAD

**Issue by Ravi1971** [TestStack/White#470]
Trying to install testStack.white via nugget package manager in Visual studio 2015.  receiving following error "An error occurred while retrieving package metadata for 'TestStack.White.0.13.3' from source 'nuget.org' "  Need immediate help.  Let me know what is the issue ?

**Comment by maxinfet** [comment]
Sorry I saw this on Saturday but havent had a chance to get to it. I will attempt to add this to a fresh project in visual studio 2015 and see what is going on when I get home.

**Comment by maxinfet** [comment]
I create a blank WPF project in Visual Studio 2015 on Windows 10 and was able to add the TestStack.White and TestStack.White.Uia3 packages with no problems. I would delete your packages folder and make sure that your package.config doesnt have any TestStack.White elements in it and then try to install again.
