### ISSUE TITLE
How to Access the Another window which has not opened through white ?

### ISSUE THREAD

**Issue by Chandru1210** [TestStack/White#473]
Hi,

Can you please help that how to control the another window based on window name which has not been opened through white. i have some objects in power point slides that objects opens the new application window but am unable to control that window since i used the main window as ppt. 

Thanks in advance,
Chandru.

**Comment by omireault** [comment]
New applications can be attached using their PID.
Here is the code I use for this:

`Application app = null;
app = Application.Attach((int)psId);`

**Comment by Chandru1210** [comment]
Thank you. i tried with below code and it's works

var addwindow = TestStack.White.Desktop.Instance.Windows();
                for(int i =0;i<= addwindow.Count-1;i++)
                {
                 if(addwindow[i].Name.Contains("my addwindow"))
                  {
                      var button = addwindow[i].Exists<TestStack.White.UIItems.Button>(SearchCriteria.ByAutomationId("Automation id"));
                      if(button == true)
                      {
                          addwindow[i].Get<TestStack.White.UIItems.Button>(SearchCriteria.ByAutomationId("Automation id")).Click();
                      }
                  }
                }
