### ISSUE TITLE
TestStack White Crashing after Pressing Button

### ISSUE THREAD

**Issue by LeagueRaINi** [TestStack/White#479]
TestStack White crashes after Pressing a Dialog Button that disappears after Pressing "OK"
`var OK = window.Get<Button>("OK");`
`OK.Click();`

"OK.Click();" throws the exception

**Comment by tlbzeu** [comment]
Probably the ok button is a child element of an modal window so you need first to get the modal window then the button from it:
```
var modalWindow = window.ModalWindow("Dialog Title");
var OK = modalWindow.Get<Button>(SearchCriteria.ByText("OK"));
OK.Click();
```

**Comment by LeagueRaINi** [comment]
the main window is a MFC Dialog with no Window Name
but i will try this thanks
