### ISSUE TITLE
WPF datagrid

### ISSUE THREAD

**Issue by kappa10j** [TestStack/White#483]
I have a listview whose cells are a custom type so the Cells property of listviewrow doesn't see it
actionListener.ActionPerforming(this);
                var collection = finder.Descendants(
                        new AutomationSearchCondition(
                            new OrCondition(
                                AutomationSearchCondition.ByControlType(ControlType.Text).Condition,
                                AutomationSearchCondition.ByControlType(ControlType.CheckBox).Condition,
                                AutomationSearchCondition.ByControlType(ControlType.ComboBox).Condition,
                                AutomationSearchCondition.ByControlType(ControlType.Image).Condition)));
                return new ListViewCells(collection, actionListener, header);

I've tried adding AutomationSearchCondition.ByControlType(ControlType.Custom).Condition to the OrCondition and it will then find my cells.  Without recompiling from the source, is there a way to override that in my own code easily?

**Comment by kappa10j** [comment]
The only way I can think of is to create MyListView deriving from ListView and override get:Rows.  Then create a MyListViewRows deriving from ListViewRows and override get:Cells.  I will also need to create MyListViewRowFactory and MyListViewRows.  This seems like a lot but the only way I can think of.

**Comment by Roemer** [comment]
With White, this is currently the way to go. For this case, you could use FlaUI which is independent of ControlTypes and you can convert the elements to whatever you want.
