### ISSUE TITLE
Treenode fetch taking time in TestStack White.Please suggest some solution.

### ISSUE THREAD

**Issue by sumesh-m** [TestStack/White#485]
Hi 
I am using the below code to fetch the tree node 
AutomationElement parentNode = win32TreeNode.AutomationElement.GetUpdatedCache(CacheRequest.Current);AutomationElement childNode = null;
 childNode = parentNode.FindFirst(TreeScope.Children, new PropertyCondition(AutomationElement.NameProperty, childNodeId));

This code taking more time to fetch the node .Since the node is created dynamically from application we need to call this code again and again to get updated value.
Is there any suggestion to speed up this process.
Also if we need to get the updated value second time whether we need to call FindFirst() again ?Or is there any other way we can get the updated node?
Please provide sample snippet if possible.

**Comment by maninwindow** [comment]
@sumesh-m  https://github.com/TestStack/White/issues/484
