### ISSUE TITLE
Next Release?

### ISSUE THREAD

**Issue by ReservedDeveloper** [TestStack/White#496]
It appears that there have been several commits to master since the last release of this library in 2014. Are there plans to tag another release in the near future, or is this project in a maintenance mode or abandoned state?

**Comment by JakeGinnivan** [comment]
There is a gitter channel with some interest in moving things forward. I am not using White and haven't in quite some time. 

White needs someone, or multiple people to pick up the torch. There are a few other projects forked off White which with help could come back in for a next version which fixes many of the current issues.

But best bet is to jump onto the gitter channel and chat to the people there

**Comment by ReservedDeveloper** [comment]
Naturally, it was all of five minutes after posting that I saw the bit in the readme talking about the inactive state of the project. Thanks for the quick update, though! I'll explore some of those avenues you mentioned.
