### ISSUE TITLE
how to select the unvisible treenode

### ISSUE THREAD

**Issue by jialius** [TestStack/White#506]
this is WPF treenode, i must select treenode's text .but there are many treenodes, i can't select unvisible treenode with scrollbar

**Comment by Roemer** [comment]
Wow, hard to know what you exactly want.
I guess you have a virtualized tree where some items are not visible without scrolling to them. There are multiple approaches here.
1. Use the ScrollItemPattern and call ScrollIntoView
2. Use the VirtualizedItemPattern and realize the item you want.
3. Use the ScrollPattern to scroll down until the item is found. 
4. Use the scrollbars or mouse wheel to scroll to the item.

For realizing virtual items, FlaUI has a helper where you can look: https://github.com/Roemer/FlaUI/blob/master/src/FlaUI.Core/Tools/ItemRealizer.cs

If you do have some xaml you could post would help as well.

**Comment by jialius** [comment]
for example: i want to select the last treenode, but i can't use "node.GetElement(SearchCriteria.ByClassName("TextBlock"))" get the node' text, becase there are many treenodes cause the lase node can't see in the tree

**Comment by Roemer** [comment]
Sounds that (as I wrote above) your tree is virtualized. Please post a screenshot showing the tree and a tree-item in inspect/uiaverify/FlaUInspect

**Comment by jialius** [comment]
![s61221-170641 1](https://cloud.githubusercontent.com/assets/23051218/21383327/c9c1630a-c72a-11e6-83dd-99f3f3b1659c.jpg)

**Comment by jialius** [comment]
like this ,i can't select treenode that i can't see

**Comment by Roemer** [comment]
What do you mean by "can't see"? Does UIA see it? If so, use the ScrollIntoView method.

**Comment by jialius** [comment]
ScrollItemPattern scp = node.AutomationElement.GetCurrentPattern(ScrollItemPattern.Pattern) as ScrollItemPattern;
                scp.ScrollIntoView();
thanks
