### ISSUE TITLE
Name Property not returning expected value

### ISSUE THREAD

**Issue by mpape23** [TestStack/White#508]
I have a button defined in WPF:
` <Button Name="button123" Content="Customer123"/>`

Getting the button by name works as expected:
`var btn= commandBar.Get<Button>("Button123");`

but getting the name back again shows "Customer123"
`var btnName= btn.Name; //returns "Customer123"`

digging deaper into [teststack code ](https://github.com/TestStack/White/blob/master/src/TestStack.White/UIItems/UIItem.cs)shows that the name is got by:
automationElement.Current.Name; 

but its not clear from the MSDN [documentation ](https://msdn.microsoft.com/en-us/library/system.windows.automation.automationelement.automationelementinformation.name(v=vs.110).aspx ) as to why this means the Content property ("Customer123") is found instead of the Name property ("Button123").

Even though this looks like a Microsoft implementation I would like a mechanism to retrieve the button Name property explicitly, not let automationelementinformation.name decide to pick the Content property.

**Comment by Roemer** [comment]
You are mixing UIA concepts with WPF concepts.
The UIA name is usually the text or content of a control. The "id" or WPFs Name is the AutomationId from UIA perspective.

**Comment by mpape23** [comment]
I see so switch to 
` <Button AutomationProperties.AutomationId="button123" Content="Customer123"/> `

then find the button use
 var btn= commandBar.Get<Button>("Button123"); 
 var btnName= btn.Id; //now returns "Button123"

**Comment by Roemer** [comment]
Yes, this is the correct approach. As for this issue, I think you should close it since the Name property returns what is expected (and that is what the UIA provider returns for the Name, see https://msdn.microsoft.com/en-us/library/ms742153(v=vs.110).aspx for example for the button, there you see the NameProperty returns "The name of the button control is the text that is used to label it.").
