### ISSUE TITLE
How to access the Iframe from the InternerExplorerWindow

### ISSUE THREAD

**Issue by JoaoFelipePego** [TestStack/White#514]
I have a web page that contains an Iframe with a Flash application inside it, how do I access the content inside the Iframe by the TestStack.White Library?

>`<iframe src="https://www.mypage.com/iframe/?locale=en_US&amp;baseShowoffUrl%2Fshow-off" id="my-guest-app" scrolling="no" frameborder="0" height="550" width="975"></iframe>
`
>>`[...] <object" id="FlashContainer" data="//www.mypage.com/iframe/web/flash/SysLoader.swf?cl=23323" type="application/x-shockwave-flash" height="550" width="975"><param value="true" name="allowFullScreenInteractive"><param value="//www.mypage.com/iframe/web/flash/" name="base"><param value="always" name="allowscriptaccess"><param value="gpu" name="wmode"><param value="false" name="menu"></object> [...]`

It would be something similar to what Selenium WebDriver does with the following command:

` driver.SwitchTo().Frame(0);
`

I need to automate the testing of an application in FLASH that for security reasons stays inside an Iframe ...

Is this possible?

**Comment by Roemer** [comment]
Did you try finding with with any inspect tool? They "should" appear somewhere as a pane. In general, ui automation based in UIA (like White or FlaUI) are not really great for automating browsers, Selenium is much better there.
