### ISSUE TITLE
How to check if text on UIItem is truncated

### ISSUE THREAD

**Issue by EyalShlomi** [TestStack/White#519]
HI all,

My mission is to 'scan' the target application UI Items (Buttons, labels, dialogs ...) and to check if the text on the item is truncated or not, (Note: the target app needs to support X languages).
So, for example I see that the TextBox.Text & TextBox.BulkText both are loaded with the 'full text'.
then I tried to use the UIA to do somting like:
System.Drawing.Size _size = System.Windows.Forms.TextRenderer.MeasureText(_textBox.Text, _textBox.Font);
  in order to do something like: if (_textBox.Bounds.size.width <= size) 
But How do I get the font size???

BTW, if you have any ideas how to it in another way I happy to hear it!

Thanks in advance !

**Comment by dpisanu** [comment]
Hi,

Where is the truncation happening?
Speaking from a WPF perspective, there are so many spots where you can do
the truncation and most of then are not reflected in UIA.
As you are saying that the full text is loaded, the underlying ViewModel is
obviously presenting the full content and leaving it up to some render
logic to do the truncation.

I do not recall how it is in WinForms but in WPF there is the auto
truncation transformation on Text controls. Maybe there is a pattern you
need to expose to check that.

**Comment by EyalShlomi** [comment]
HI  dpisanu and thanks for replaying.
First I must admit that I'm a new to .NET / C# / UI ... (I used to be a C/C++ Real Time developer years ago...)
So please walk me through all the information you need and I will try to get it.
Now, regarding your Q: "Where is the truncation happening?", lets assume I have a button with "login" on it as a text, and now I change the language of the UI of the target application to German, and now login is written "Anmeldung" (a bit longer), and due to the fact that the button size is fixed, the text is "Anmeld...". 
Hope this helps.

**Comment by dpisanu** [comment]
Servus,

I understood your situation first time round. :)

Let me try to explain the situation in easier terms.
The Button us being created with a set of data. Fixed size for width and
height and location in the UI. The text value is taken via some sort of
binding.
(Be it a direct binding in xaml or a button.text setting routine in the
code behind)
Best case, the text fits perfectly in the button.
Worst case, the text extends outside of the button or is hard truncated.

What designers usually do is implement some truncation logic to append
ellipsis (the ... at the end) if the text is longer then allowed.

This truncation can either be done on the source data or in the visual
representation part.

In your case it seems like the truncation is being performed in the UI
control by either
A) some fancy custom UI mechanism
B) a framework mechanism (e.g. https://wpf.2000things.com/tag/texttrimming/)

In both situations, the UI control is actually created with the full text
when it comes to UIA but what is send to the renderer for visual
presentation is the truncated form.

This is something UIA can not catch.
Maybe you can export some custom UI pattern to bring the truncated text out
or you could give the TreeWalker a shot if that one can catch it.
https://msdn.microsoft.com/en-us/library/system.windows.automation.treewalker.treewalker.aspx

If you are working on a wpf application you could try hacking snoop into
your test setup.
Snoop will be able to get the truncated text.
This will be painfull though. We gave up on that task.

**Comment by EyalShlomi** [comment]
thanks!

**Comment by EyalShlomi** [comment]
Staying on this issue,
Can I get the font width that is used in the current window / UI control?

**Comment by dpisanu** [comment]
On the note of custom patterns. Read up on this here.
https://blogs.msdn.microsoft.com/winuiautomation/2010/12/27/uia-custom-patterns-part-3/

Now in regards of font.
This again is a pure visualization topic and is afaik not accessible via
uia.

**Comment by lerthe61** [comment]
And even if you find font name (FontFamily name) that does not help you a lot. Because you need to keep in mind font substitution (if user does not have required font then font rendering choose another font that close enough)
