### ISSUE TITLE
unable to initialize the Automation.AutomationElement

### ISSUE THREAD

**Issue by MonoAutomation** [TestStack/White#521]
Hi,

i have created a couple of test projects using UIAcomwrapper and working fine .but suddenly i am getting the following error

**An exception of type 'System.TypeInitializationException' occurred in mytest.dll but was not handled in user code
Additional information: The type initializer for 'System.Windows.Automation.AutomationElement' threw an exception.
If there is a handler for this exception, the program may be safely continued.**

Code:
```
public class TestClass
    {
        [DllImport("user32.dll", CharSet = CharSet.Unicode)]
        internal static extern IntPtr FindWindow([In] string className, [In] string windowName);
        private IntPtr TargetHandle;
        private AutomationElement RootElement;
	//private string winTitle="some title";
	 public bool TestPr(string winTitle)
        {
		TargetHandle = FindWindow(null, winTitle);
                 System.Console.WriteLine("The current window handle : " + TargetHandle);

                if (TargetHandle == IntPtr.Zero)
                {
               //some message
		}
		RootElement = AutomationElement.FromHandle(TargetHandle); 
                **_//here am getting the error_**           
	        System.Console.WriteLine(TargetHandle);
	}
![automatioelementexception](https://cloud.githubusercontent.com/assets/1586248/22402654/44603db6-e625-11e6-91f9-cbead0471999.jpg)

```
Can any one assist me to fix this issue?

more info, if i call the above method from test class...it is going through and working fine as expected.

this is actually ,i have created a dll(COM visible) and calling from vbscript ...when i call from vbscript it is returning application/window handle id but failing at **FromHadle**

vbscript code:
Set myObj=CreateObject("MyTest.TestClass")
title="Automation Application World"
objTest=myObj.TestPr(title)

Is anything wrong in the title format?

**Comment by MonoAutomation** [comment]
Its a dll compilation issues and got fixed.

**Comment by SharonJacob** [comment]
@MonoAutomation  How did you fix this exception?

**Comment by MonoAutomation** [comment]
Hi,

I have embedded the required dlls and called the method which i have created.always we need to create embedded dlls if we want to share with other clients(3rd party) ,ex: if you want create and use it in qtp.
while creating any customized dll ,you need to convert normal dll to embedded dll that whichever you are referring dll(any dll ex: teststack white)  in your project.

embedded: yes in google you will get lot of information ob it.

still if you have issues you can approach me.
