### ISSUE TITLE
Is White compatible with Direct2D ?

### ISSUE THREAD

**Issue by ph-ms** [TestStack/White#522]
Direct2D isn't uncommon in a WPF application. Can white automate it?

**Comment by Roemer** [comment]
If the parts that are rendered with Direct2D supports automation peers it can.

**Comment by ph-ms** [comment]
Do you know if anyone has ever done it? Maybe they did, but didn't write up a case study or blog entry about it...

**Comment by Roemer** [comment]
I think it is kind of similar to a custom control. See here for an entry point: https://msdn.microsoft.com/en-us/library/cc165614(v=vs.110).aspx
