### ISSUE TITLE
Combobox select issue

### ISSUE THREAD

**Issue by schaithanya** [TestStack/White#523]
I am using infragisitics controls in my application and currently trying to automate it with Teststack.White framework.

I am unable to select item in a combo box which is in one of the grid cell.

I am able to capture the combo box control with items but when I call the select method it leads to the following exception :

Specified method is not supported at Infragisitics.Win.Valuelist.ValuelistBaseUIAProviderStub.System.Windows.Automation.Provider.iselectionitemprovider.Select()

**Comment by Roemer** [comment]
Seems like Infragistics hasn't implemented that. Ask them to implement it or use workarounds like key presses or mouse clicks.
