### ISSUE TITLE
Select ListItem in Combobox by text 

### ISSUE THREAD

**Issue by Eewa** [TestStack/White#553]
Hi,
Can you help me out how to get a list item from combo box? I have a combo box as AutomationElement, obtained from IUItem
var comboBox = custom.GetElement(SearchCriteria.ByControlType(ControlType.ComboBox).AndAutomationId("comboBoxAutomationId")). 
This combo box contains list items which contains text. I would like to select the item according to given text. 
I am able to find the item:
AutomationElement listItem = comboBox.FindFirst(TreeScope.Subtree, new PropertyCondition(AutomationElement.NameProperty, item));

but the listItem is TextBlock without any pattern to select the item.

Thanks in advance!

![screenshot_024](https://cloud.githubusercontent.com/assets/27963584/25343504/8b433ba2-290f-11e7-90c6-3bb6d7f47213.png)

**Comment by Roemer** [comment]
You can either use the treewalker to select the parent (the list item) and select that one or use a mouse click on the text item.

**Comment by Eewa** [comment]
Thank you for your comment. I tried to use the mouse click, but it was not working. 
There is no clickable point on my list item.
I guess it could be because the item is off screen.  :-(
I would like to then use the treewalker, but I do not know how. 
Could you, please, give me some hints.

Thank you very much

**Comment by Roemer** [comment]
If it is offscreen it might be easier to loop thru all list items, scroll them into view and then get the child "text" element and check if it matches your text.
For the treewalker approach, there is a UIItemExtensions class which has a GetParent method to get the parent. Or you can use the System.Windows.Automation.TreeWalker yourself.

**Comment by Eewa** [comment]
Great! I looped thru and it worked. Thank you very much!
