### ISSUE TITLE
Cannot access ItemsControl by name

### ISSUE THREAD

**Issue by lafather** [TestStack/White#560]
Hello, dear developers!

I have given some name to my ItemsControl. Now I am trying to access it from the test. Unfortunately, SearchCriteria.ByAutomationId does not work for me, in addition, I cannot see any matching control type from your solution. Would you mind hinting me an approach for looking up such controls by automation ID (or in any other way)?

Thanks in advance,
Vitalii Feilo

**Comment by Roemer** [comment]
Please post a screenshot of Inspect/FlaUInspect/UIAVerify.

**Comment by lafather** [comment]
I have already found a workaround. Sorry about wasting your time. 
Good luck!
