### ISSUE TITLE
Is white automation tool supported on Windows 10/Getwindow is not working on windows 10

### ISSUE THREAD

**Issue by ngupta2734** [TestStack/White#570]
I am executing a simple code to launch calculator app on **Window 10 OS.**
I am getting error below on GetWindow:-
 "An unhandled exception of type 'TestStack.White.AutomationException' occurred in TestStack.White.dll
Additional information: Couldn't find window with title Calculator in process 17460, after waiting for 30 seconds".

I have created Windows form application project with below code.
The same code is working on Windows 7 OS. Can someone please help on how to use Getwindow object on windows 10 or if anyone know if White tool is supported on windows 10.
```csharp
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using System.Diagnostics;
using TestStack.White;
using TestStack.White.Bricks;
using TestStack.White.Factory;
using TestStack.White.UIItems.Finders;
using TestStack.White.InputDevices;
using TestStack.White.UIItems.WindowItems;
using TestStack.White.Configuration;
using TestStack.White.UIA;
using TestStack.White.UIItems;
using TestStack.White.WindowsAPI;
using System.Windows;


namespace Check1
{
    public partial class Form1 : Form
    {
        public Form1()
        {
            InitializeComponent();
        }

        private void Form1_Load(object sender, EventArgs e)
        {
            TestStack.White.Application application = TestStack.White.Application.Launch(@"C:\Windows\system32\calc.exe");
           Window window = application.GetWindow("Calculator", InitializeOption.NoCache);
            //Window window = application.GetWindow(TestStack.White.UIItems.Finders.SearchCriteria.ByText("Calculator"), InitializeOption.NoCache);
        }
    }
}
```

**Comment by ngupta2734** [comment]
Any help on this topic would be appreciated

**Comment by Roemer** [comment]
First of all, the windows 10 calculator is a windows universal app which should be started differently.
Second, White uses UIA2 which does not really support WPF or Universal apps.
You therefore have two choices:
1. Use the partially working UIAComWrapper branch from White
2. Switch to an alternative which supports UIA3 (like https://github.com/Roemer/FlaUI)

**Comment by ngupta2734** [comment]
Thanks for the comments. I tried the following 2 approaches on Windows 10 after adding UIA3 using 
Install-Package FlaUI.UIA3 -Version 1.2.0:-

1)For console project, getting error  "Application does not contain a definition for 'GetMainWindow" and no extension method 'GetMainwindow' accepting a first argument of type "application" could be found.:-

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Diagnostics;
using TestStack.White;
using TestStack.White.Bricks;
using TestStack.White.Factory;
using TestStack.White.UIItems.Finders;
using TestStack.White.InputDevices;
using TestStack.White.UIItems.WindowItems;
using TestStack.White.Configuration;
using TestStack.White.UIA;
using TestStack.White.UIItems;
using TestStack.White.WindowsAPI;
using System.Windows;
using FlaUI.UIA3;

namespace ConsoleApplication4
{
    class Program
    {
        public static object MessageBox { get; private set; }

        static void Main(string[] args)
        {



            var app = Application.Launch("calc.exe");
            using (var automation = new UIA3Automation())
            {
                var window = app.GetMainWindow(automation);
                var button1 = window.FindFirstDescentant(cf => cf.ByText("1"))?.AsButton();
                button1?.Invoke();


            }

        }
    }
}



2)On using Windows form application project,I am getting error "Application does not contain a definition for Launch".

using FlaUI.UIA3;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace WindowsFormsApplication5
{
    public partial class Form1 : Form
    {
        public Form1()
        {
            InitializeComponent();
        }

        private void Form1_Load(object sender, EventArgs e)
        {
            var app = Application.Launch("calc.exe");
            using (var automation = new UIA3Automation())
            {
                var window = app.GetMainWindow(automation);
                var button1 = window.FindFirstDescentant(cf => cf.ByText("1"))?.AsButton();
                button1?.Invoke();

            }
        }
    }
}

**Comment by ngupta2734** [comment]
Can you please help on how to fix  these..

**Comment by Roemer** [comment]
If you have issues with FlaUI, you should post that on FlaUIs issues page. For the calculator, here is a working example with the win10 calculator in FlaUI:
https://github.com/Roemer/FlaUI/blob/master/src/FlaUI.Core.UITests/CalculatorTests.cs

**Comment by ngupta2734** [comment]
Thank you
