### ISSUE TITLE
read text subitems of listitems

### ISSUE THREAD

**Issue by elmicka** [TestStack/White#571]
Hi all
I'm facing an issue using teststack to automate some Windows (OS) native windows.
I'm automating some tests on the sound devices management window (mmsys.cpl). In this window, recording and playback devices are listed in a listview, with multiple informations inside (name, full name, state, ...).
But, with automation framework, that listview is considered as a listbox, and consequently the children items as listboxitems, having nothing more than a single value of text.
But for my tests, I need to get access to those listboxitems subitems, especially the full name of the device.
using a tool to inspect the UI (inspect.exe from the windows sdk toolkit eg), I can find those sub elements in the tree, text items as children of the litboxitem.
please find some screenshots attached and a simple sample code.
any help would be great
thank's.

here is my sample code (full sample available as attachement )

```C#
string searchSoundWindowName = "Son";//localize string regarding OS culture

            //open sound management window
            string path = Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.System), "mmsys.cpl");
            Process proc = new Process();
            proc.StartInfo = new ProcessStartInfo() { CreateNoWindow = false, WindowStyle = ProcessWindowStyle.Normal, FileName = path };
            proc.Start();
            proc.WaitForExit(10000);

            Thread.Sleep(1000);

            //find the sound management window handle
            var soundwindow = GetOpenedWindows()[searchSoundWindowName];

            ////bring window to front
            //SetForegroundWindow(soundwindow.Item1);

            //get a wrapper to the sound window application
            var soundapp = TestStack.White.Application.Attach((int)soundwindow.Item2);

            //get the sound management window automation element
            var window = soundapp.GetWindow(searchSoundWindowName, InitializeOption.NoCache);

            //search for sound window tab control automation element
            var tabControl = window.Get<TestStack.White.UIItems.TabItems.Tab>(SearchCriteria.ByAutomationId("12320"));

            //get tabs
            var tabs = tabControl.Pages;

            //get recording tab
            var tab = tabs[1];

            //select recording tab
            tab.Select();

            //get devices listbox
            var listbox = tab.Get<TestStack.White.UIItems.ListBoxItems.ListBox>(SearchCriteria.ByAutomationId("1000"));

            var listitems = listbox.Items;

            foreach (var listitem in listitems)
            {
                //select list item
                listitem.Click();

                //here i would like to access the subitems text to do some checks before opening device properties dialog...
            }
```

here is the window I'm automating 

![2017-08-16 12_08_54-son](https://user-images.githubusercontent.com/31065248/29358790-976b615e-827c-11e7-876a-edebd5dbd73f.png)

here is my listbox automation inspector 

![2017-08-16 12_10_03-inspect hwnd_ 0x000c0a04 uiaccess](https://user-images.githubusercontent.com/31065248/29360184-08a57cba-8282-11e7-9bb0-5a25cf4f6c60.png)

here is my listboxitem automation inspector 

![2017-08-16 12_13_16-inspect hwnd_ 0x000c0a04 uiaccess](https://user-images.githubusercontent.com/31065248/29358844-d37bf5dc-827c-11e7-95f0-c75f4a2761f3.png)

and here is the subelements i want to get access to 

![2017-08-16 12_21_28-inspect hwnd_ 0x000c0a04 uiaccess](https://user-images.githubusercontent.com/31065248/29359040-977f867e-827d-11e7-81a5-808484ca1f89.png)

sample code below (consider changing the sound manager window name regarding your os culture, main.cs line 20) 

[ConsoleApplication2.zip](https://github.com/TestStack/White/files/1227845/ConsoleApplication2.zip)

**Comment by Roemer** [comment]
The "White" way to do it would be to use the WPFUIItem extension classes to get a "Raw" ui item (container) where you can find subitems.
In my opinion a better way would be to switch to FlaUI, which works with "raw" items and has other advantages ;)

I adjusted your application to FlaUI (you just need to add FlaUI.UIA3 from NuGet):
```csharp
tatic void Main(string[] args)
{
    string searchSoundWindowName = "Sound"; //localize string regarding OS culture

    //open sound management window
    string path = Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.System), "mmsys.cpl");
    Process proc = new Process();
    proc.StartInfo = new ProcessStartInfo() { CreateNoWindow = false, WindowStyle = ProcessWindowStyle.Normal, FileName = path };
    proc.Start();
    proc.WaitForExit(10000);

    Thread.Sleep(1000);

    //find the sound management window handle
    var soundwindow = GetOpenedWindows()[searchSoundWindowName];

    ////bring window to front
    //SetForegroundWindow(soundwindow.Item1);

    //get a wrapper to the sound window application
    var soundapp = Application.Attach((int)soundwindow.Item2);
    using (var uia = new UIA3Automation())
    {
        // var window = soundapp.GetMainWindow(uia);

        var window = uia.GetDesktop().FindFirstChild(cf => cf.ByProcessId(soundapp.ProcessId));

        //search for sound window tab control automation element
        var tabControl = window.FindFirstChild(cf => cf.ByAutomationId("12320")).AsTab();

        //get tabs
        var tabs = tabControl.TabItems;

        //get recording tab
        var tab = tabs[1];

        //select recording tab
        tab.Select();

        //get devices listbox (in UIA3 it is on the main window)
        var listbox = window.FindFirstChild(cf => cf.ByAutomationId("1000"));

        var listitems = listbox.FindAllChildren();

        foreach (var listitem in listitems)
        {
            //select list item
            listitem.Click();

            //here i would like to access the subitems text to do some checks before opening device properties dialog...
            var listItemDetails = listitem.FindAllChildren();
            foreach (var listItemDetail in listItemDetails)
            {
                Console.WriteLine(listItemDetail.AsLabel().Text);
            }
        }
        Console.ReadKey();
    }
}
```

**Comment by elmicka** [comment]
Thank you @Roemer, I'm gonna try this immediately

**Comment by elmicka** [comment]
Hi again @Roemer ,
I tested your code sample and unfortunately the children list remains empty, same as I get with AutomationElement.FindAll(...) method 
Did it return something for you?
here is the sample code that adapted a little bit to get it working on my environement, maybe it depends on which os version we are running (windows 7 for me)


`
 //get a wrapper to the sound window application
            var soundapp = Application.Attach(handle);
            using (var uia = new UIA3Automation())
            {
                var window = uia.GetDesktop().FindFirstChild(cf => cf.ByProcessId(soundapp.ProcessId));

                //search for sound window tab control automation element
                var tabControl = window.FindFirstChild(cf => cf.ByAutomationId("12320")).AsTab();

                //get tabs
                var tabs = tabControl.TabItems;

                //get recording tab
                var tab = tabs[1];

                //select recording tab
                tab.Select();

                //get devices listbox (in UIA3 it is on the main window)
                **//maybe it is different regarding the os version? under win7 the listbox belongs to the tabcontrol**
                var listbox = **tab**.FindFirstChild(cf => cf.ByAutomationId("1000"));

                **//add control type condition to avoid scrollbar (first child)**
                var listitems = listbox.FindAllChildren( ch => ch.ByControlType(FlaUI.Core.Definitions.ControlType.ListItem));

                foreach (var listitem in listitems)
                {
                    //select list item
                    listitem.Click();

                    //here i would like to access the subitems text to do some checks before opening device properties dialog...
                    var listItemDetails = listitem.FindAllChildren();

                    **//empty :(**

                    foreach (var listItemDetail in listItemDetails)
                    {
                        Console.WriteLine(listItemDetail.AsLabel().Text);
                    }
                }

                Console.ReadKey();
            }
        }
`

**Comment by Roemer** [comment]
Yes it worked for me with Win 8. can you show a screenshot of flauinspect with uia3 showing it? You can also try UIA2 which is what white uses.

**Comment by elmicka** [comment]
OK thank's i'll do that as soon as i'll get back to work on tomorrow morning, will keep you in touch

**Comment by elmicka** [comment]
hi again
so, I inspected the forms with FlaUInspect

With UIA2 MANAGED, I cannot see the children labels under the listbox item

![2017-08-17 09_28_33-flauinspect v1 2 0 uia2 managed](https://user-images.githubusercontent.com/31065248/29402030-b756c8d4-8333-11e7-8935-d9f263fae839.png)


whereas I can see them with UIA3 INTEROP

![2017-08-17 09_29_30-flauinspect v1 2 0 uia3 interop](https://user-images.githubusercontent.com/31065248/29402032-bb9748ba-8333-11e7-8d75-811e593e1204.png)


so it looks like I should be able to see them, but my "allchildren" list from the listboxitem is still empty

![2017-08-17 10_02_41-coreaudiosample debugging - microsoft visual studio administrator](https://user-images.githubusercontent.com/31065248/29402038-bec4071c-8333-11e7-8f0f-f9a71c14f375.png)


I guess there might be a mystic cast or something else. As I downloaded FlaUInspect source code, I'm gonna try to have a look on it, to check what I could have missed

**Comment by Roemer** [comment]
It does the same, FlaUInspect uses FlaUI to show the tree.
Two things you can check:
1. Are you using FlaUI.UIA3 and not FlaUI.UIA2?
2. Maybe try running your programm (or Visual Studio) elevated (as Admin) and see if that helps.

**Comment by elmicka** [comment]
Hi @Roemer 
I was well using UIA3, and my VS was running as Admin too
But, good news today, I finnaly got it working!
You were right, using FlaUI, the devices listbox (#1000) belongs to the window, and is not considered as a child of the tab... despite it's displayed as it in the window treeview
Moreover, I think I had some code mistakes or misunderstoods, maybe not using the good types or not making the good casts, a mix of UIA types and UIAutomation types, ... I can't really get what was happening, but now with this sample (and easier) code I can finally get my list box items sub items! and do what I need to do with... because the aim of all of that is to be able to find a device regarding a given name and change its state, that's why I really needed to acces the subitems where the real device name is displayed, not the ugly "Microphone" or "Speaker" text. 
By the way, I find that kind of weird that Microsoft has decided to display the device type first in this list, instead of its real name... anyway...

```C#
static void Main(string[] args)
        {
            string searchSoundWindowName = "Son"; //localize string regarding OS culture       

            using (var auto = new UIA3Automation())
            {
                //try to get the sound management window
                var window = auto.GetDesktop().FindFirstChild(c => auto.ConditionFactory.ByName(searchSoundWindowName));

                if (null == window)//seems like sound management window is not opened
                {
                    //start sound management window
                    string path = Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.System), "mmsys.cpl");
                    Process proc = new Process();
                    proc.StartInfo = new ProcessStartInfo() { CreateNoWindow = false, WindowStyle = ProcessWindowStyle.Normal, FileName = path };
                    proc.Start();
                    proc.WaitForExit(10000);
                    Thread.Sleep(1000);//just wait a little bit to ensure the window is well opened

                    //try again to get the sound management window
                    window = auto.GetDesktop().FindFirstChild(c => auto.ConditionFactory.ByName(searchSoundWindowName));
                }

                //search for sound window tab control
                //and select recording tab
                window.FindFirstChild(cf => cf.ByAutomationId("12320")).AsTab().SelectTabItem(1);

                //get devices listbox
                var listbox = window.FindFirstChild(window.ConditionFactory.ByAutomationId("1000"));

                //get devices list items
                var listitems = listbox.FindAll(TreeScope.Children, window.ConditionFactory.ByControlType(ControlType.ListItem), TimeSpan.Zero);

                StringBuilder bld;

                foreach (var li in listitems)
                {
                    bld = new StringBuilder();

                    bld.AppendLine(li.Properties.Name);
                    bld.AppendLine("{");

                    var subitems = li.FindAllChildren(li.ConditionFactory.ByControlType(ControlType.Text));

                    foreach (var sub in subitems)
                    {
                        bld.AppendFormat("\t{0}",sub.Properties.Name);
                        bld.AppendLine();
                    }

                    bld.AppendLine("}");
                    bld.AppendLine();

                    Console.WriteLine(bld.ToString());
                }

            }

            Console.ReadKey();
        }
```

And there here is my ouput :

![2017-08-18 11_11_15-2017-08-18 11_03_07-file____c__users_mriviere_downloads_coreaudio_coreaudio_core](https://user-images.githubusercontent.com/31065248/29452345-4a2e7d46-8406-11e7-9cbc-78af5a037312.png)


Now I'm gonna implement user audio device management in our test automation framework based on that sample code and that lib.

So thank you very much for your helpful hand!

**Comment by Roemer** [comment]
Great to hear it works for you now!
If you have further questions about FlaUI or ideas how it can be improved, head over to FlaUIs GitHub and report the issue there.
