### ISSUE TITLE
TestStack.White.UIItems.WIndowItems.Window.WaitForWindow() throws a timeout occurred exception for a WPF application that uses backstage view

### ISSUE THREAD

**Issue by ktenedios** [TestStack/White#584]
An automation test engineer and I are currently evaluating TestStack.White for suitability for automated UI tests for a WPF application that our company has released. This WPF application makes use of backstage view for operations such as creating a new project.

The issue that we are experiencing (using 0.13.2) is that for a test that clicks a button, we get an exception thrown (Timeout occurred) by the method `WaitForWindow()` in the class `TestStack.White.UIItems.WIndowItems.Window`. What we have found is that if lines 223-227 in Window.cs are commented out, TestStack.White is recompiled and the test is run with the updated TestStack.White binary, this issue does not occur.

A PDF has been attached to better illustrate what we are trying to do, and the point where the error occurs.
[Backstage view issue on button click.pdf](https://github.com/TestStack/White/files/1602023/Backstage.view.issue.on.button.click.pdf)

I do not particularly like the hack that I implemented on my end, as of course I do not know what issues this would cause further down the line. If further detail is required please let me know.

**Comment by Roemer** [comment]
I suggest switching to [FlaUI](https://github.com/Roemer/FlaUI) as this is actively maintained and also better supports WPF applications with the interop (UIA3) version.

**Comment by ktenedios** [comment]
Hi again, after some further investigation I found that I needed to use the TestStack.White.Uia3 NuGet package instead of the TestStack.White NuGet package. After changing packages I found that this issue did not surface.

**Comment by Roemer** [comment]
Any reasons why you didn‘t try FlaUI?
