### ISSUE TITLE
Not able to retrieve a winForm window from a WPF application during splashScreen

### ISSUE THREAD

**Issue by Sl1ckR1ck** [TestStack/White#615]
Hi all,

ok this may be a twisted case, but in our application we have a validation process that occurs during the Application.xaml.vb OnStartup method.

Basically if the validation fails we use a legacy Windows Form message (from another library) to show a error message and then close the application after the user clicked OK.

The problem is that this WindowsForms is nowhere to be found. 

If i look in _application.GetWindows  there is 0 windows.

If i look in TestStack.White.Desktop.Instance.Windows, none of those windows if my window desired.

Also this winForm window is not shown in the task manager since it is part of the application process.

With Microsoft UI Test Recorder, i am able to find the control and replay my tests.

Any clues of what is wrong? Am i doing something wrong?

**Comment by Roemer** [comment]
See attached issue from FlaUI, would be similar in White but staying with FlaUI is a wise choice ;)
