### ISSUE TITLE
Obtaining Word\Excel MenuBar

### ISSUE THREAD

**Issue by ant-howell** [TestStack/White#95]
Hi

Having a little trouble obtaining the Excel or Word MenuBar control.

Using VisualUIA the location of the MenuBar is deep through a few "pane" controls which might be the issue. The "Options" (from File->Options) menu for Excel 2010 is a "NavBarMenu" control entitled "File" 4 levels deep.  

MenuBar menuBar = mainWin.GetMenuBar(SearchCriteria.ByText("File"))

Does not detect it and I'm wondering if the depth of the search is insufficient. The older White library had a global configuration file which could be set to X levels search depth. Is there a equivalent for TestStack.White? 

Or.....

an override search level whilst searching for Menu Items?

Any help will be appreciated.

Ant

Additional

Setting CoreAppXmlConfiguration.Instance.MaxElementSearchDepth = 10 does not make any difference in this instance.

**Comment by YossiCohen** [comment]
Hi, Sorry for the somehow nonrelated question,
can you select cells or activate addins with White?
